/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.voole.hobbit2.hive.order.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class HiveOrderDryRecord extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"HiveOrderDryRecord\",\"namespace\":\"com.voole.hobbit2.hive.order.avro\",\"fields\":[{\"name\":\"sessID\",\"type\":\"string\"},{\"name\":\"UID\",\"type\":[\"string\",\"null\"]},{\"name\":\"HID\",\"type\":[\"string\",\"null\"]},{\"name\":\"OEMID\",\"type\":[\"long\",\"null\"]},{\"name\":\"natip\",\"type\":[\"long\",\"null\"]},{\"name\":\"FID\",\"type\":[\"string\",\"null\"]},{\"name\":\"playBgnTime\",\"type\":[\"long\",\"null\"]},{\"name\":\"playAliveTime\",\"type\":[\"long\",\"null\"]},{\"name\":\"playEndTime\",\"type\":[\"long\",\"null\"]},{\"name\":\"playDurationTime\",\"type\":[\"long\",\"null\"]},{\"name\":\"avgspeed\",\"type\":[\"long\",\"null\"]},{\"name\":\"isAdMod\",\"type\":\"boolean\",\"default\":false},{\"name\":\"isRepeatMod\",\"type\":\"boolean\",\"default\":false},{\"name\":\"pid\",\"type\":[\"string\",\"null\"]},{\"name\":\"epgid\",\"type\":[\"long\",\"null\"]},{\"name\":\"secid\",\"type\":[\"string\",\"null\"]},{\"name\":\"datasorce\",\"type\":[\"int\",\"null\"]},{\"name\":\"metric_status\",\"type\":[\"int\",\"null\"]},{\"name\":\"metric_techtype\",\"type\":[\"int\",\"null\"]},{\"name\":\"playurl\",\"type\":[\"string\",\"null\"]},{\"name\":\"apk_version\",\"type\":[\"string\",\"null\"]},{\"name\":\"dim_po_id\",\"type\":[\"int\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence sessID;
  @Deprecated public java.lang.CharSequence UID;
  @Deprecated public java.lang.CharSequence HID;
  @Deprecated public java.lang.Long OEMID;
  @Deprecated public java.lang.Long natip;
  @Deprecated public java.lang.CharSequence FID;
  @Deprecated public java.lang.Long playBgnTime;
  @Deprecated public java.lang.Long playAliveTime;
  @Deprecated public java.lang.Long playEndTime;
  @Deprecated public java.lang.Long playDurationTime;
  @Deprecated public java.lang.Long avgspeed;
  @Deprecated public boolean isAdMod;
  @Deprecated public boolean isRepeatMod;
  @Deprecated public java.lang.CharSequence pid;
  @Deprecated public java.lang.Long epgid;
  @Deprecated public java.lang.CharSequence secid;
  @Deprecated public java.lang.Integer datasorce;
  @Deprecated public java.lang.Integer metric_status;
  @Deprecated public java.lang.Integer metric_techtype;
  @Deprecated public java.lang.CharSequence playurl;
  @Deprecated public java.lang.CharSequence apk_version;
  @Deprecated public java.lang.Integer dim_po_id;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public HiveOrderDryRecord() {}

  /**
   * All-args constructor.
   */
  public HiveOrderDryRecord(java.lang.CharSequence sessID, java.lang.CharSequence UID, java.lang.CharSequence HID, java.lang.Long OEMID, java.lang.Long natip, java.lang.CharSequence FID, java.lang.Long playBgnTime, java.lang.Long playAliveTime, java.lang.Long playEndTime, java.lang.Long playDurationTime, java.lang.Long avgspeed, java.lang.Boolean isAdMod, java.lang.Boolean isRepeatMod, java.lang.CharSequence pid, java.lang.Long epgid, java.lang.CharSequence secid, java.lang.Integer datasorce, java.lang.Integer metric_status, java.lang.Integer metric_techtype, java.lang.CharSequence playurl, java.lang.CharSequence apk_version, java.lang.Integer dim_po_id) {
    this.sessID = sessID;
    this.UID = UID;
    this.HID = HID;
    this.OEMID = OEMID;
    this.natip = natip;
    this.FID = FID;
    this.playBgnTime = playBgnTime;
    this.playAliveTime = playAliveTime;
    this.playEndTime = playEndTime;
    this.playDurationTime = playDurationTime;
    this.avgspeed = avgspeed;
    this.isAdMod = isAdMod;
    this.isRepeatMod = isRepeatMod;
    this.pid = pid;
    this.epgid = epgid;
    this.secid = secid;
    this.datasorce = datasorce;
    this.metric_status = metric_status;
    this.metric_techtype = metric_techtype;
    this.playurl = playurl;
    this.apk_version = apk_version;
    this.dim_po_id = dim_po_id;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sessID;
    case 1: return UID;
    case 2: return HID;
    case 3: return OEMID;
    case 4: return natip;
    case 5: return FID;
    case 6: return playBgnTime;
    case 7: return playAliveTime;
    case 8: return playEndTime;
    case 9: return playDurationTime;
    case 10: return avgspeed;
    case 11: return isAdMod;
    case 12: return isRepeatMod;
    case 13: return pid;
    case 14: return epgid;
    case 15: return secid;
    case 16: return datasorce;
    case 17: return metric_status;
    case 18: return metric_techtype;
    case 19: return playurl;
    case 20: return apk_version;
    case 21: return dim_po_id;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sessID = (java.lang.CharSequence)value$; break;
    case 1: UID = (java.lang.CharSequence)value$; break;
    case 2: HID = (java.lang.CharSequence)value$; break;
    case 3: OEMID = (java.lang.Long)value$; break;
    case 4: natip = (java.lang.Long)value$; break;
    case 5: FID = (java.lang.CharSequence)value$; break;
    case 6: playBgnTime = (java.lang.Long)value$; break;
    case 7: playAliveTime = (java.lang.Long)value$; break;
    case 8: playEndTime = (java.lang.Long)value$; break;
    case 9: playDurationTime = (java.lang.Long)value$; break;
    case 10: avgspeed = (java.lang.Long)value$; break;
    case 11: isAdMod = (java.lang.Boolean)value$; break;
    case 12: isRepeatMod = (java.lang.Boolean)value$; break;
    case 13: pid = (java.lang.CharSequence)value$; break;
    case 14: epgid = (java.lang.Long)value$; break;
    case 15: secid = (java.lang.CharSequence)value$; break;
    case 16: datasorce = (java.lang.Integer)value$; break;
    case 17: metric_status = (java.lang.Integer)value$; break;
    case 18: metric_techtype = (java.lang.Integer)value$; break;
    case 19: playurl = (java.lang.CharSequence)value$; break;
    case 20: apk_version = (java.lang.CharSequence)value$; break;
    case 21: dim_po_id = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sessID' field.
   */
  public java.lang.CharSequence getSessID() {
    return sessID;
  }

  /**
   * Sets the value of the 'sessID' field.
   * @param value the value to set.
   */
  public void setSessID(java.lang.CharSequence value) {
    this.sessID = value;
  }

  /**
   * Gets the value of the 'UID' field.
   */
  public java.lang.CharSequence getUID() {
    return UID;
  }

  /**
   * Sets the value of the 'UID' field.
   * @param value the value to set.
   */
  public void setUID(java.lang.CharSequence value) {
    this.UID = value;
  }

  /**
   * Gets the value of the 'HID' field.
   */
  public java.lang.CharSequence getHID() {
    return HID;
  }

  /**
   * Sets the value of the 'HID' field.
   * @param value the value to set.
   */
  public void setHID(java.lang.CharSequence value) {
    this.HID = value;
  }

  /**
   * Gets the value of the 'OEMID' field.
   */
  public java.lang.Long getOEMID() {
    return OEMID;
  }

  /**
   * Sets the value of the 'OEMID' field.
   * @param value the value to set.
   */
  public void setOEMID(java.lang.Long value) {
    this.OEMID = value;
  }

  /**
   * Gets the value of the 'natip' field.
   */
  public java.lang.Long getNatip() {
    return natip;
  }

  /**
   * Sets the value of the 'natip' field.
   * @param value the value to set.
   */
  public void setNatip(java.lang.Long value) {
    this.natip = value;
  }

  /**
   * Gets the value of the 'FID' field.
   */
  public java.lang.CharSequence getFID() {
    return FID;
  }

  /**
   * Sets the value of the 'FID' field.
   * @param value the value to set.
   */
  public void setFID(java.lang.CharSequence value) {
    this.FID = value;
  }

  /**
   * Gets the value of the 'playBgnTime' field.
   */
  public java.lang.Long getPlayBgnTime() {
    return playBgnTime;
  }

  /**
   * Sets the value of the 'playBgnTime' field.
   * @param value the value to set.
   */
  public void setPlayBgnTime(java.lang.Long value) {
    this.playBgnTime = value;
  }

  /**
   * Gets the value of the 'playAliveTime' field.
   */
  public java.lang.Long getPlayAliveTime() {
    return playAliveTime;
  }

  /**
   * Sets the value of the 'playAliveTime' field.
   * @param value the value to set.
   */
  public void setPlayAliveTime(java.lang.Long value) {
    this.playAliveTime = value;
  }

  /**
   * Gets the value of the 'playEndTime' field.
   */
  public java.lang.Long getPlayEndTime() {
    return playEndTime;
  }

  /**
   * Sets the value of the 'playEndTime' field.
   * @param value the value to set.
   */
  public void setPlayEndTime(java.lang.Long value) {
    this.playEndTime = value;
  }

  /**
   * Gets the value of the 'playDurationTime' field.
   */
  public java.lang.Long getPlayDurationTime() {
    return playDurationTime;
  }

  /**
   * Sets the value of the 'playDurationTime' field.
   * @param value the value to set.
   */
  public void setPlayDurationTime(java.lang.Long value) {
    this.playDurationTime = value;
  }

  /**
   * Gets the value of the 'avgspeed' field.
   */
  public java.lang.Long getAvgspeed() {
    return avgspeed;
  }

  /**
   * Sets the value of the 'avgspeed' field.
   * @param value the value to set.
   */
  public void setAvgspeed(java.lang.Long value) {
    this.avgspeed = value;
  }

  /**
   * Gets the value of the 'isAdMod' field.
   */
  public java.lang.Boolean getIsAdMod() {
    return isAdMod;
  }

  /**
   * Sets the value of the 'isAdMod' field.
   * @param value the value to set.
   */
  public void setIsAdMod(java.lang.Boolean value) {
    this.isAdMod = value;
  }

  /**
   * Gets the value of the 'isRepeatMod' field.
   */
  public java.lang.Boolean getIsRepeatMod() {
    return isRepeatMod;
  }

  /**
   * Sets the value of the 'isRepeatMod' field.
   * @param value the value to set.
   */
  public void setIsRepeatMod(java.lang.Boolean value) {
    this.isRepeatMod = value;
  }

  /**
   * Gets the value of the 'pid' field.
   */
  public java.lang.CharSequence getPid() {
    return pid;
  }

  /**
   * Sets the value of the 'pid' field.
   * @param value the value to set.
   */
  public void setPid(java.lang.CharSequence value) {
    this.pid = value;
  }

  /**
   * Gets the value of the 'epgid' field.
   */
  public java.lang.Long getEpgid() {
    return epgid;
  }

  /**
   * Sets the value of the 'epgid' field.
   * @param value the value to set.
   */
  public void setEpgid(java.lang.Long value) {
    this.epgid = value;
  }

  /**
   * Gets the value of the 'secid' field.
   */
  public java.lang.CharSequence getSecid() {
    return secid;
  }

  /**
   * Sets the value of the 'secid' field.
   * @param value the value to set.
   */
  public void setSecid(java.lang.CharSequence value) {
    this.secid = value;
  }

  /**
   * Gets the value of the 'datasorce' field.
   */
  public java.lang.Integer getDatasorce() {
    return datasorce;
  }

  /**
   * Sets the value of the 'datasorce' field.
   * @param value the value to set.
   */
  public void setDatasorce(java.lang.Integer value) {
    this.datasorce = value;
  }

  /**
   * Gets the value of the 'metric_status' field.
   */
  public java.lang.Integer getMetricStatus() {
    return metric_status;
  }

  /**
   * Sets the value of the 'metric_status' field.
   * @param value the value to set.
   */
  public void setMetricStatus(java.lang.Integer value) {
    this.metric_status = value;
  }

  /**
   * Gets the value of the 'metric_techtype' field.
   */
  public java.lang.Integer getMetricTechtype() {
    return metric_techtype;
  }

  /**
   * Sets the value of the 'metric_techtype' field.
   * @param value the value to set.
   */
  public void setMetricTechtype(java.lang.Integer value) {
    this.metric_techtype = value;
  }

  /**
   * Gets the value of the 'playurl' field.
   */
  public java.lang.CharSequence getPlayurl() {
    return playurl;
  }

  /**
   * Sets the value of the 'playurl' field.
   * @param value the value to set.
   */
  public void setPlayurl(java.lang.CharSequence value) {
    this.playurl = value;
  }

  /**
   * Gets the value of the 'apk_version' field.
   */
  public java.lang.CharSequence getApkVersion() {
    return apk_version;
  }

  /**
   * Sets the value of the 'apk_version' field.
   * @param value the value to set.
   */
  public void setApkVersion(java.lang.CharSequence value) {
    this.apk_version = value;
  }

  /**
   * Gets the value of the 'dim_po_id' field.
   */
  public java.lang.Integer getDimPoId() {
    return dim_po_id;
  }

  /**
   * Sets the value of the 'dim_po_id' field.
   * @param value the value to set.
   */
  public void setDimPoId(java.lang.Integer value) {
    this.dim_po_id = value;
  }

  /** Creates a new HiveOrderDryRecord RecordBuilder */
  public static com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder newBuilder() {
    return new com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder();
  }
  
  /** Creates a new HiveOrderDryRecord RecordBuilder by copying an existing Builder */
  public static com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder newBuilder(com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder other) {
    return new com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder(other);
  }
  
  /** Creates a new HiveOrderDryRecord RecordBuilder by copying an existing HiveOrderDryRecord instance */
  public static com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder newBuilder(com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord other) {
    return new com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder(other);
  }
  
  /**
   * RecordBuilder for HiveOrderDryRecord instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<HiveOrderDryRecord>
    implements org.apache.avro.data.RecordBuilder<HiveOrderDryRecord> {

    private java.lang.CharSequence sessID;
    private java.lang.CharSequence UID;
    private java.lang.CharSequence HID;
    private java.lang.Long OEMID;
    private java.lang.Long natip;
    private java.lang.CharSequence FID;
    private java.lang.Long playBgnTime;
    private java.lang.Long playAliveTime;
    private java.lang.Long playEndTime;
    private java.lang.Long playDurationTime;
    private java.lang.Long avgspeed;
    private boolean isAdMod;
    private boolean isRepeatMod;
    private java.lang.CharSequence pid;
    private java.lang.Long epgid;
    private java.lang.CharSequence secid;
    private java.lang.Integer datasorce;
    private java.lang.Integer metric_status;
    private java.lang.Integer metric_techtype;
    private java.lang.CharSequence playurl;
    private java.lang.CharSequence apk_version;
    private java.lang.Integer dim_po_id;

    /** Creates a new Builder */
    private Builder() {
      super(com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sessID)) {
        this.sessID = data().deepCopy(fields()[0].schema(), other.sessID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.UID)) {
        this.UID = data().deepCopy(fields()[1].schema(), other.UID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.HID)) {
        this.HID = data().deepCopy(fields()[2].schema(), other.HID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.OEMID)) {
        this.OEMID = data().deepCopy(fields()[3].schema(), other.OEMID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.natip)) {
        this.natip = data().deepCopy(fields()[4].schema(), other.natip);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.FID)) {
        this.FID = data().deepCopy(fields()[5].schema(), other.FID);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.playBgnTime)) {
        this.playBgnTime = data().deepCopy(fields()[6].schema(), other.playBgnTime);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.playAliveTime)) {
        this.playAliveTime = data().deepCopy(fields()[7].schema(), other.playAliveTime);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.playEndTime)) {
        this.playEndTime = data().deepCopy(fields()[8].schema(), other.playEndTime);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.playDurationTime)) {
        this.playDurationTime = data().deepCopy(fields()[9].schema(), other.playDurationTime);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.avgspeed)) {
        this.avgspeed = data().deepCopy(fields()[10].schema(), other.avgspeed);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.isAdMod)) {
        this.isAdMod = data().deepCopy(fields()[11].schema(), other.isAdMod);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.isRepeatMod)) {
        this.isRepeatMod = data().deepCopy(fields()[12].schema(), other.isRepeatMod);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.pid)) {
        this.pid = data().deepCopy(fields()[13].schema(), other.pid);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.epgid)) {
        this.epgid = data().deepCopy(fields()[14].schema(), other.epgid);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.secid)) {
        this.secid = data().deepCopy(fields()[15].schema(), other.secid);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.datasorce)) {
        this.datasorce = data().deepCopy(fields()[16].schema(), other.datasorce);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.metric_status)) {
        this.metric_status = data().deepCopy(fields()[17].schema(), other.metric_status);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.metric_techtype)) {
        this.metric_techtype = data().deepCopy(fields()[18].schema(), other.metric_techtype);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.playurl)) {
        this.playurl = data().deepCopy(fields()[19].schema(), other.playurl);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.apk_version)) {
        this.apk_version = data().deepCopy(fields()[20].schema(), other.apk_version);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.dim_po_id)) {
        this.dim_po_id = data().deepCopy(fields()[21].schema(), other.dim_po_id);
        fieldSetFlags()[21] = true;
      }
    }
    
    /** Creates a Builder by copying an existing HiveOrderDryRecord instance */
    private Builder(com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord other) {
            super(com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.SCHEMA$);
      if (isValidValue(fields()[0], other.sessID)) {
        this.sessID = data().deepCopy(fields()[0].schema(), other.sessID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.UID)) {
        this.UID = data().deepCopy(fields()[1].schema(), other.UID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.HID)) {
        this.HID = data().deepCopy(fields()[2].schema(), other.HID);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.OEMID)) {
        this.OEMID = data().deepCopy(fields()[3].schema(), other.OEMID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.natip)) {
        this.natip = data().deepCopy(fields()[4].schema(), other.natip);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.FID)) {
        this.FID = data().deepCopy(fields()[5].schema(), other.FID);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.playBgnTime)) {
        this.playBgnTime = data().deepCopy(fields()[6].schema(), other.playBgnTime);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.playAliveTime)) {
        this.playAliveTime = data().deepCopy(fields()[7].schema(), other.playAliveTime);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.playEndTime)) {
        this.playEndTime = data().deepCopy(fields()[8].schema(), other.playEndTime);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.playDurationTime)) {
        this.playDurationTime = data().deepCopy(fields()[9].schema(), other.playDurationTime);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.avgspeed)) {
        this.avgspeed = data().deepCopy(fields()[10].schema(), other.avgspeed);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.isAdMod)) {
        this.isAdMod = data().deepCopy(fields()[11].schema(), other.isAdMod);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.isRepeatMod)) {
        this.isRepeatMod = data().deepCopy(fields()[12].schema(), other.isRepeatMod);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.pid)) {
        this.pid = data().deepCopy(fields()[13].schema(), other.pid);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.epgid)) {
        this.epgid = data().deepCopy(fields()[14].schema(), other.epgid);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.secid)) {
        this.secid = data().deepCopy(fields()[15].schema(), other.secid);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.datasorce)) {
        this.datasorce = data().deepCopy(fields()[16].schema(), other.datasorce);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.metric_status)) {
        this.metric_status = data().deepCopy(fields()[17].schema(), other.metric_status);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.metric_techtype)) {
        this.metric_techtype = data().deepCopy(fields()[18].schema(), other.metric_techtype);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.playurl)) {
        this.playurl = data().deepCopy(fields()[19].schema(), other.playurl);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.apk_version)) {
        this.apk_version = data().deepCopy(fields()[20].schema(), other.apk_version);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.dim_po_id)) {
        this.dim_po_id = data().deepCopy(fields()[21].schema(), other.dim_po_id);
        fieldSetFlags()[21] = true;
      }
    }

    /** Gets the value of the 'sessID' field */
    public java.lang.CharSequence getSessID() {
      return sessID;
    }
    
    /** Sets the value of the 'sessID' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setSessID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.sessID = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'sessID' field has been set */
    public boolean hasSessID() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'sessID' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearSessID() {
      sessID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'UID' field */
    public java.lang.CharSequence getUID() {
      return UID;
    }
    
    /** Sets the value of the 'UID' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setUID(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.UID = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'UID' field has been set */
    public boolean hasUID() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'UID' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearUID() {
      UID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'HID' field */
    public java.lang.CharSequence getHID() {
      return HID;
    }
    
    /** Sets the value of the 'HID' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setHID(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.HID = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'HID' field has been set */
    public boolean hasHID() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'HID' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearHID() {
      HID = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'OEMID' field */
    public java.lang.Long getOEMID() {
      return OEMID;
    }
    
    /** Sets the value of the 'OEMID' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setOEMID(java.lang.Long value) {
      validate(fields()[3], value);
      this.OEMID = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'OEMID' field has been set */
    public boolean hasOEMID() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'OEMID' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearOEMID() {
      OEMID = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'natip' field */
    public java.lang.Long getNatip() {
      return natip;
    }
    
    /** Sets the value of the 'natip' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setNatip(java.lang.Long value) {
      validate(fields()[4], value);
      this.natip = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'natip' field has been set */
    public boolean hasNatip() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'natip' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearNatip() {
      natip = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'FID' field */
    public java.lang.CharSequence getFID() {
      return FID;
    }
    
    /** Sets the value of the 'FID' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setFID(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.FID = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'FID' field has been set */
    public boolean hasFID() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'FID' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearFID() {
      FID = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'playBgnTime' field */
    public java.lang.Long getPlayBgnTime() {
      return playBgnTime;
    }
    
    /** Sets the value of the 'playBgnTime' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setPlayBgnTime(java.lang.Long value) {
      validate(fields()[6], value);
      this.playBgnTime = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'playBgnTime' field has been set */
    public boolean hasPlayBgnTime() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'playBgnTime' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearPlayBgnTime() {
      playBgnTime = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'playAliveTime' field */
    public java.lang.Long getPlayAliveTime() {
      return playAliveTime;
    }
    
    /** Sets the value of the 'playAliveTime' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setPlayAliveTime(java.lang.Long value) {
      validate(fields()[7], value);
      this.playAliveTime = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'playAliveTime' field has been set */
    public boolean hasPlayAliveTime() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'playAliveTime' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearPlayAliveTime() {
      playAliveTime = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'playEndTime' field */
    public java.lang.Long getPlayEndTime() {
      return playEndTime;
    }
    
    /** Sets the value of the 'playEndTime' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setPlayEndTime(java.lang.Long value) {
      validate(fields()[8], value);
      this.playEndTime = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'playEndTime' field has been set */
    public boolean hasPlayEndTime() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'playEndTime' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearPlayEndTime() {
      playEndTime = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'playDurationTime' field */
    public java.lang.Long getPlayDurationTime() {
      return playDurationTime;
    }
    
    /** Sets the value of the 'playDurationTime' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setPlayDurationTime(java.lang.Long value) {
      validate(fields()[9], value);
      this.playDurationTime = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'playDurationTime' field has been set */
    public boolean hasPlayDurationTime() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'playDurationTime' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearPlayDurationTime() {
      playDurationTime = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /** Gets the value of the 'avgspeed' field */
    public java.lang.Long getAvgspeed() {
      return avgspeed;
    }
    
    /** Sets the value of the 'avgspeed' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setAvgspeed(java.lang.Long value) {
      validate(fields()[10], value);
      this.avgspeed = value;
      fieldSetFlags()[10] = true;
      return this; 
    }
    
    /** Checks whether the 'avgspeed' field has been set */
    public boolean hasAvgspeed() {
      return fieldSetFlags()[10];
    }
    
    /** Clears the value of the 'avgspeed' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearAvgspeed() {
      avgspeed = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /** Gets the value of the 'isAdMod' field */
    public java.lang.Boolean getIsAdMod() {
      return isAdMod;
    }
    
    /** Sets the value of the 'isAdMod' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setIsAdMod(boolean value) {
      validate(fields()[11], value);
      this.isAdMod = value;
      fieldSetFlags()[11] = true;
      return this; 
    }
    
    /** Checks whether the 'isAdMod' field has been set */
    public boolean hasIsAdMod() {
      return fieldSetFlags()[11];
    }
    
    /** Clears the value of the 'isAdMod' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearIsAdMod() {
      fieldSetFlags()[11] = false;
      return this;
    }

    /** Gets the value of the 'isRepeatMod' field */
    public java.lang.Boolean getIsRepeatMod() {
      return isRepeatMod;
    }
    
    /** Sets the value of the 'isRepeatMod' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setIsRepeatMod(boolean value) {
      validate(fields()[12], value);
      this.isRepeatMod = value;
      fieldSetFlags()[12] = true;
      return this; 
    }
    
    /** Checks whether the 'isRepeatMod' field has been set */
    public boolean hasIsRepeatMod() {
      return fieldSetFlags()[12];
    }
    
    /** Clears the value of the 'isRepeatMod' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearIsRepeatMod() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /** Gets the value of the 'pid' field */
    public java.lang.CharSequence getPid() {
      return pid;
    }
    
    /** Sets the value of the 'pid' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setPid(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.pid = value;
      fieldSetFlags()[13] = true;
      return this; 
    }
    
    /** Checks whether the 'pid' field has been set */
    public boolean hasPid() {
      return fieldSetFlags()[13];
    }
    
    /** Clears the value of the 'pid' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearPid() {
      pid = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /** Gets the value of the 'epgid' field */
    public java.lang.Long getEpgid() {
      return epgid;
    }
    
    /** Sets the value of the 'epgid' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setEpgid(java.lang.Long value) {
      validate(fields()[14], value);
      this.epgid = value;
      fieldSetFlags()[14] = true;
      return this; 
    }
    
    /** Checks whether the 'epgid' field has been set */
    public boolean hasEpgid() {
      return fieldSetFlags()[14];
    }
    
    /** Clears the value of the 'epgid' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearEpgid() {
      epgid = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /** Gets the value of the 'secid' field */
    public java.lang.CharSequence getSecid() {
      return secid;
    }
    
    /** Sets the value of the 'secid' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setSecid(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.secid = value;
      fieldSetFlags()[15] = true;
      return this; 
    }
    
    /** Checks whether the 'secid' field has been set */
    public boolean hasSecid() {
      return fieldSetFlags()[15];
    }
    
    /** Clears the value of the 'secid' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearSecid() {
      secid = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /** Gets the value of the 'datasorce' field */
    public java.lang.Integer getDatasorce() {
      return datasorce;
    }
    
    /** Sets the value of the 'datasorce' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setDatasorce(java.lang.Integer value) {
      validate(fields()[16], value);
      this.datasorce = value;
      fieldSetFlags()[16] = true;
      return this; 
    }
    
    /** Checks whether the 'datasorce' field has been set */
    public boolean hasDatasorce() {
      return fieldSetFlags()[16];
    }
    
    /** Clears the value of the 'datasorce' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearDatasorce() {
      datasorce = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /** Gets the value of the 'metric_status' field */
    public java.lang.Integer getMetricStatus() {
      return metric_status;
    }
    
    /** Sets the value of the 'metric_status' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setMetricStatus(java.lang.Integer value) {
      validate(fields()[17], value);
      this.metric_status = value;
      fieldSetFlags()[17] = true;
      return this; 
    }
    
    /** Checks whether the 'metric_status' field has been set */
    public boolean hasMetricStatus() {
      return fieldSetFlags()[17];
    }
    
    /** Clears the value of the 'metric_status' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearMetricStatus() {
      metric_status = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /** Gets the value of the 'metric_techtype' field */
    public java.lang.Integer getMetricTechtype() {
      return metric_techtype;
    }
    
    /** Sets the value of the 'metric_techtype' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setMetricTechtype(java.lang.Integer value) {
      validate(fields()[18], value);
      this.metric_techtype = value;
      fieldSetFlags()[18] = true;
      return this; 
    }
    
    /** Checks whether the 'metric_techtype' field has been set */
    public boolean hasMetricTechtype() {
      return fieldSetFlags()[18];
    }
    
    /** Clears the value of the 'metric_techtype' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearMetricTechtype() {
      metric_techtype = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /** Gets the value of the 'playurl' field */
    public java.lang.CharSequence getPlayurl() {
      return playurl;
    }
    
    /** Sets the value of the 'playurl' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setPlayurl(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.playurl = value;
      fieldSetFlags()[19] = true;
      return this; 
    }
    
    /** Checks whether the 'playurl' field has been set */
    public boolean hasPlayurl() {
      return fieldSetFlags()[19];
    }
    
    /** Clears the value of the 'playurl' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearPlayurl() {
      playurl = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /** Gets the value of the 'apk_version' field */
    public java.lang.CharSequence getApkVersion() {
      return apk_version;
    }
    
    /** Sets the value of the 'apk_version' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setApkVersion(java.lang.CharSequence value) {
      validate(fields()[20], value);
      this.apk_version = value;
      fieldSetFlags()[20] = true;
      return this; 
    }
    
    /** Checks whether the 'apk_version' field has been set */
    public boolean hasApkVersion() {
      return fieldSetFlags()[20];
    }
    
    /** Clears the value of the 'apk_version' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearApkVersion() {
      apk_version = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /** Gets the value of the 'dim_po_id' field */
    public java.lang.Integer getDimPoId() {
      return dim_po_id;
    }
    
    /** Sets the value of the 'dim_po_id' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder setDimPoId(java.lang.Integer value) {
      validate(fields()[21], value);
      this.dim_po_id = value;
      fieldSetFlags()[21] = true;
      return this; 
    }
    
    /** Checks whether the 'dim_po_id' field has been set */
    public boolean hasDimPoId() {
      return fieldSetFlags()[21];
    }
    
    /** Clears the value of the 'dim_po_id' field */
    public com.voole.hobbit2.hive.order.avro.HiveOrderDryRecord.Builder clearDimPoId() {
      dim_po_id = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    @Override
    public HiveOrderDryRecord build() {
      try {
        HiveOrderDryRecord record = new HiveOrderDryRecord();
        record.sessID = fieldSetFlags()[0] ? this.sessID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.UID = fieldSetFlags()[1] ? this.UID : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.HID = fieldSetFlags()[2] ? this.HID : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.OEMID = fieldSetFlags()[3] ? this.OEMID : (java.lang.Long) defaultValue(fields()[3]);
        record.natip = fieldSetFlags()[4] ? this.natip : (java.lang.Long) defaultValue(fields()[4]);
        record.FID = fieldSetFlags()[5] ? this.FID : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.playBgnTime = fieldSetFlags()[6] ? this.playBgnTime : (java.lang.Long) defaultValue(fields()[6]);
        record.playAliveTime = fieldSetFlags()[7] ? this.playAliveTime : (java.lang.Long) defaultValue(fields()[7]);
        record.playEndTime = fieldSetFlags()[8] ? this.playEndTime : (java.lang.Long) defaultValue(fields()[8]);
        record.playDurationTime = fieldSetFlags()[9] ? this.playDurationTime : (java.lang.Long) defaultValue(fields()[9]);
        record.avgspeed = fieldSetFlags()[10] ? this.avgspeed : (java.lang.Long) defaultValue(fields()[10]);
        record.isAdMod = fieldSetFlags()[11] ? this.isAdMod : (java.lang.Boolean) defaultValue(fields()[11]);
        record.isRepeatMod = fieldSetFlags()[12] ? this.isRepeatMod : (java.lang.Boolean) defaultValue(fields()[12]);
        record.pid = fieldSetFlags()[13] ? this.pid : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.epgid = fieldSetFlags()[14] ? this.epgid : (java.lang.Long) defaultValue(fields()[14]);
        record.secid = fieldSetFlags()[15] ? this.secid : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.datasorce = fieldSetFlags()[16] ? this.datasorce : (java.lang.Integer) defaultValue(fields()[16]);
        record.metric_status = fieldSetFlags()[17] ? this.metric_status : (java.lang.Integer) defaultValue(fields()[17]);
        record.metric_techtype = fieldSetFlags()[18] ? this.metric_techtype : (java.lang.Integer) defaultValue(fields()[18]);
        record.playurl = fieldSetFlags()[19] ? this.playurl : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.apk_version = fieldSetFlags()[20] ? this.apk_version : (java.lang.CharSequence) defaultValue(fields()[20]);
        record.dim_po_id = fieldSetFlags()[21] ? this.dim_po_id : (java.lang.Integer) defaultValue(fields()[21]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
