/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.voole.hobbit2.camus.bsepg;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class BsEpgPlayInfo extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BsEpgPlayInfo\",\"namespace\":\"com.voole.hobbit2.camus.bsepg\",\"fields\":[{\"name\":\"sessID\",\"type\":[\"long\",\"null\"]},{\"name\":\"playbgntime\",\"type\":[\"long\",\"null\"]},{\"name\":\"playalivetime\",\"type\":[\"long\",\"null\"]},{\"name\":\"playendtime\",\"type\":[\"long\",\"null\"]},{\"name\":\"hid\",\"type\":[\"string\",\"null\"]},{\"name\":\"userip\",\"type\":[\"string\",\"null\"]},{\"name\":\"oemid\",\"type\":[\"long\",\"null\"]},{\"name\":\"playurl\",\"type\":[\"string\",\"null\"]},{\"name\":\"perfip\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.Long sessID;
  @Deprecated public java.lang.Long playbgntime;
  @Deprecated public java.lang.Long playalivetime;
  @Deprecated public java.lang.Long playendtime;
  @Deprecated public java.lang.CharSequence hid;
  @Deprecated public java.lang.CharSequence userip;
  @Deprecated public java.lang.Long oemid;
  @Deprecated public java.lang.CharSequence playurl;
  @Deprecated public java.lang.CharSequence perfip;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public BsEpgPlayInfo() {}

  /**
   * All-args constructor.
   */
  public BsEpgPlayInfo(java.lang.Long sessID, java.lang.Long playbgntime, java.lang.Long playalivetime, java.lang.Long playendtime, java.lang.CharSequence hid, java.lang.CharSequence userip, java.lang.Long oemid, java.lang.CharSequence playurl, java.lang.CharSequence perfip) {
    this.sessID = sessID;
    this.playbgntime = playbgntime;
    this.playalivetime = playalivetime;
    this.playendtime = playendtime;
    this.hid = hid;
    this.userip = userip;
    this.oemid = oemid;
    this.playurl = playurl;
    this.perfip = perfip;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sessID;
    case 1: return playbgntime;
    case 2: return playalivetime;
    case 3: return playendtime;
    case 4: return hid;
    case 5: return userip;
    case 6: return oemid;
    case 7: return playurl;
    case 8: return perfip;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sessID = (java.lang.Long)value$; break;
    case 1: playbgntime = (java.lang.Long)value$; break;
    case 2: playalivetime = (java.lang.Long)value$; break;
    case 3: playendtime = (java.lang.Long)value$; break;
    case 4: hid = (java.lang.CharSequence)value$; break;
    case 5: userip = (java.lang.CharSequence)value$; break;
    case 6: oemid = (java.lang.Long)value$; break;
    case 7: playurl = (java.lang.CharSequence)value$; break;
    case 8: perfip = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sessID' field.
   */
  public java.lang.Long getSessID() {
    return sessID;
  }

  /**
   * Sets the value of the 'sessID' field.
   * @param value the value to set.
   */
  public void setSessID(java.lang.Long value) {
    this.sessID = value;
  }

  /**
   * Gets the value of the 'playbgntime' field.
   */
  public java.lang.Long getPlaybgntime() {
    return playbgntime;
  }

  /**
   * Sets the value of the 'playbgntime' field.
   * @param value the value to set.
   */
  public void setPlaybgntime(java.lang.Long value) {
    this.playbgntime = value;
  }

  /**
   * Gets the value of the 'playalivetime' field.
   */
  public java.lang.Long getPlayalivetime() {
    return playalivetime;
  }

  /**
   * Sets the value of the 'playalivetime' field.
   * @param value the value to set.
   */
  public void setPlayalivetime(java.lang.Long value) {
    this.playalivetime = value;
  }

  /**
   * Gets the value of the 'playendtime' field.
   */
  public java.lang.Long getPlayendtime() {
    return playendtime;
  }

  /**
   * Sets the value of the 'playendtime' field.
   * @param value the value to set.
   */
  public void setPlayendtime(java.lang.Long value) {
    this.playendtime = value;
  }

  /**
   * Gets the value of the 'hid' field.
   */
  public java.lang.CharSequence getHid() {
    return hid;
  }

  /**
   * Sets the value of the 'hid' field.
   * @param value the value to set.
   */
  public void setHid(java.lang.CharSequence value) {
    this.hid = value;
  }

  /**
   * Gets the value of the 'userip' field.
   */
  public java.lang.CharSequence getUserip() {
    return userip;
  }

  /**
   * Sets the value of the 'userip' field.
   * @param value the value to set.
   */
  public void setUserip(java.lang.CharSequence value) {
    this.userip = value;
  }

  /**
   * Gets the value of the 'oemid' field.
   */
  public java.lang.Long getOemid() {
    return oemid;
  }

  /**
   * Sets the value of the 'oemid' field.
   * @param value the value to set.
   */
  public void setOemid(java.lang.Long value) {
    this.oemid = value;
  }

  /**
   * Gets the value of the 'playurl' field.
   */
  public java.lang.CharSequence getPlayurl() {
    return playurl;
  }

  /**
   * Sets the value of the 'playurl' field.
   * @param value the value to set.
   */
  public void setPlayurl(java.lang.CharSequence value) {
    this.playurl = value;
  }

  /**
   * Gets the value of the 'perfip' field.
   */
  public java.lang.CharSequence getPerfip() {
    return perfip;
  }

  /**
   * Sets the value of the 'perfip' field.
   * @param value the value to set.
   */
  public void setPerfip(java.lang.CharSequence value) {
    this.perfip = value;
  }

  /** Creates a new BsEpgPlayInfo RecordBuilder */
  public static com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder newBuilder() {
    return new com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder();
  }
  
  /** Creates a new BsEpgPlayInfo RecordBuilder by copying an existing Builder */
  public static com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder newBuilder(com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder other) {
    return new com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder(other);
  }
  
  /** Creates a new BsEpgPlayInfo RecordBuilder by copying an existing BsEpgPlayInfo instance */
  public static com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder newBuilder(com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo other) {
    return new com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder(other);
  }
  
  /**
   * RecordBuilder for BsEpgPlayInfo instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BsEpgPlayInfo>
    implements org.apache.avro.data.RecordBuilder<BsEpgPlayInfo> {

    private java.lang.Long sessID;
    private java.lang.Long playbgntime;
    private java.lang.Long playalivetime;
    private java.lang.Long playendtime;
    private java.lang.CharSequence hid;
    private java.lang.CharSequence userip;
    private java.lang.Long oemid;
    private java.lang.CharSequence playurl;
    private java.lang.CharSequence perfip;

    /** Creates a new Builder */
    private Builder() {
      super(com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sessID)) {
        this.sessID = data().deepCopy(fields()[0].schema(), other.sessID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.playbgntime)) {
        this.playbgntime = data().deepCopy(fields()[1].schema(), other.playbgntime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.playalivetime)) {
        this.playalivetime = data().deepCopy(fields()[2].schema(), other.playalivetime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.playendtime)) {
        this.playendtime = data().deepCopy(fields()[3].schema(), other.playendtime);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.hid)) {
        this.hid = data().deepCopy(fields()[4].schema(), other.hid);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.userip)) {
        this.userip = data().deepCopy(fields()[5].schema(), other.userip);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.oemid)) {
        this.oemid = data().deepCopy(fields()[6].schema(), other.oemid);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.playurl)) {
        this.playurl = data().deepCopy(fields()[7].schema(), other.playurl);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.perfip)) {
        this.perfip = data().deepCopy(fields()[8].schema(), other.perfip);
        fieldSetFlags()[8] = true;
      }
    }
    
    /** Creates a Builder by copying an existing BsEpgPlayInfo instance */
    private Builder(com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo other) {
            super(com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.SCHEMA$);
      if (isValidValue(fields()[0], other.sessID)) {
        this.sessID = data().deepCopy(fields()[0].schema(), other.sessID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.playbgntime)) {
        this.playbgntime = data().deepCopy(fields()[1].schema(), other.playbgntime);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.playalivetime)) {
        this.playalivetime = data().deepCopy(fields()[2].schema(), other.playalivetime);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.playendtime)) {
        this.playendtime = data().deepCopy(fields()[3].schema(), other.playendtime);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.hid)) {
        this.hid = data().deepCopy(fields()[4].schema(), other.hid);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.userip)) {
        this.userip = data().deepCopy(fields()[5].schema(), other.userip);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.oemid)) {
        this.oemid = data().deepCopy(fields()[6].schema(), other.oemid);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.playurl)) {
        this.playurl = data().deepCopy(fields()[7].schema(), other.playurl);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.perfip)) {
        this.perfip = data().deepCopy(fields()[8].schema(), other.perfip);
        fieldSetFlags()[8] = true;
      }
    }

    /** Gets the value of the 'sessID' field */
    public java.lang.Long getSessID() {
      return sessID;
    }
    
    /** Sets the value of the 'sessID' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder setSessID(java.lang.Long value) {
      validate(fields()[0], value);
      this.sessID = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'sessID' field has been set */
    public boolean hasSessID() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'sessID' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder clearSessID() {
      sessID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'playbgntime' field */
    public java.lang.Long getPlaybgntime() {
      return playbgntime;
    }
    
    /** Sets the value of the 'playbgntime' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder setPlaybgntime(java.lang.Long value) {
      validate(fields()[1], value);
      this.playbgntime = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'playbgntime' field has been set */
    public boolean hasPlaybgntime() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'playbgntime' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder clearPlaybgntime() {
      playbgntime = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'playalivetime' field */
    public java.lang.Long getPlayalivetime() {
      return playalivetime;
    }
    
    /** Sets the value of the 'playalivetime' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder setPlayalivetime(java.lang.Long value) {
      validate(fields()[2], value);
      this.playalivetime = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'playalivetime' field has been set */
    public boolean hasPlayalivetime() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'playalivetime' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder clearPlayalivetime() {
      playalivetime = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'playendtime' field */
    public java.lang.Long getPlayendtime() {
      return playendtime;
    }
    
    /** Sets the value of the 'playendtime' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder setPlayendtime(java.lang.Long value) {
      validate(fields()[3], value);
      this.playendtime = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'playendtime' field has been set */
    public boolean hasPlayendtime() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'playendtime' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder clearPlayendtime() {
      playendtime = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'hid' field */
    public java.lang.CharSequence getHid() {
      return hid;
    }
    
    /** Sets the value of the 'hid' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder setHid(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.hid = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'hid' field has been set */
    public boolean hasHid() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'hid' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder clearHid() {
      hid = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'userip' field */
    public java.lang.CharSequence getUserip() {
      return userip;
    }
    
    /** Sets the value of the 'userip' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder setUserip(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.userip = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'userip' field has been set */
    public boolean hasUserip() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'userip' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder clearUserip() {
      userip = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'oemid' field */
    public java.lang.Long getOemid() {
      return oemid;
    }
    
    /** Sets the value of the 'oemid' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder setOemid(java.lang.Long value) {
      validate(fields()[6], value);
      this.oemid = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'oemid' field has been set */
    public boolean hasOemid() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'oemid' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder clearOemid() {
      oemid = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the 'playurl' field */
    public java.lang.CharSequence getPlayurl() {
      return playurl;
    }
    
    /** Sets the value of the 'playurl' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder setPlayurl(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.playurl = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the 'playurl' field has been set */
    public boolean hasPlayurl() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the 'playurl' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder clearPlayurl() {
      playurl = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'perfip' field */
    public java.lang.CharSequence getPerfip() {
      return perfip;
    }
    
    /** Sets the value of the 'perfip' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder setPerfip(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.perfip = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'perfip' field has been set */
    public boolean hasPerfip() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'perfip' field */
    public com.voole.hobbit2.camus.bsepg.BsEpgPlayInfo.Builder clearPerfip() {
      perfip = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    public BsEpgPlayInfo build() {
      try {
        BsEpgPlayInfo record = new BsEpgPlayInfo();
        record.sessID = fieldSetFlags()[0] ? this.sessID : (java.lang.Long) defaultValue(fields()[0]);
        record.playbgntime = fieldSetFlags()[1] ? this.playbgntime : (java.lang.Long) defaultValue(fields()[1]);
        record.playalivetime = fieldSetFlags()[2] ? this.playalivetime : (java.lang.Long) defaultValue(fields()[2]);
        record.playendtime = fieldSetFlags()[3] ? this.playendtime : (java.lang.Long) defaultValue(fields()[3]);
        record.hid = fieldSetFlags()[4] ? this.hid : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.userip = fieldSetFlags()[5] ? this.userip : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.oemid = fieldSetFlags()[6] ? this.oemid : (java.lang.Long) defaultValue(fields()[6]);
        record.playurl = fieldSetFlags()[7] ? this.playurl : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.perfip = fieldSetFlags()[8] ? this.perfip : (java.lang.CharSequence) defaultValue(fields()[8]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
