// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/ApachelogPB.proto

package com.voole.hobbit.proto;

public final class ApachelogPB {
  private ApachelogPB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ApacheLogOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string serverIp = 1;
    /**
     * <code>optional string serverIp = 1;</code>
     */
    boolean hasServerIp();
    /**
     * <code>optional string serverIp = 1;</code>
     */
    java.lang.String getServerIp();
    /**
     * <code>optional string serverIp = 1;</code>
     */
    com.google.protobuf.ByteString
        getServerIpBytes();

    // optional string userIp = 2;
    /**
     * <code>optional string userIp = 2;</code>
     */
    boolean hasUserIp();
    /**
     * <code>optional string userIp = 2;</code>
     */
    java.lang.String getUserIp();
    /**
     * <code>optional string userIp = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIpBytes();

    // optional uint64 requestTime = 3;
    /**
     * <code>optional uint64 requestTime = 3;</code>
     */
    boolean hasRequestTime();
    /**
     * <code>optional uint64 requestTime = 3;</code>
     */
    long getRequestTime();

    // optional string requestMethod = 4;
    /**
     * <code>optional string requestMethod = 4;</code>
     */
    boolean hasRequestMethod();
    /**
     * <code>optional string requestMethod = 4;</code>
     */
    java.lang.String getRequestMethod();
    /**
     * <code>optional string requestMethod = 4;</code>
     */
    com.google.protobuf.ByteString
        getRequestMethodBytes();

    // optional string requestUri = 5;
    /**
     * <code>optional string requestUri = 5;</code>
     */
    boolean hasRequestUri();
    /**
     * <code>optional string requestUri = 5;</code>
     */
    java.lang.String getRequestUri();
    /**
     * <code>optional string requestUri = 5;</code>
     */
    com.google.protobuf.ByteString
        getRequestUriBytes();

    // optional string urlQueryString = 6;
    /**
     * <code>optional string urlQueryString = 6;</code>
     */
    boolean hasUrlQueryString();
    /**
     * <code>optional string urlQueryString = 6;</code>
     */
    java.lang.String getUrlQueryString();
    /**
     * <code>optional string urlQueryString = 6;</code>
     */
    com.google.protobuf.ByteString
        getUrlQueryStringBytes();

    // optional uint32 httpCode = 7;
    /**
     * <code>optional uint32 httpCode = 7;</code>
     */
    boolean hasHttpCode();
    /**
     * <code>optional uint32 httpCode = 7;</code>
     */
    int getHttpCode();

    // optional uint32 responseLen = 8;
    /**
     * <code>optional uint32 responseLen = 8;</code>
     */
    boolean hasResponseLen();
    /**
     * <code>optional uint32 responseLen = 8;</code>
     */
    int getResponseLen();

    // optional string referer = 9;
    /**
     * <code>optional string referer = 9;</code>
     */
    boolean hasReferer();
    /**
     * <code>optional string referer = 9;</code>
     */
    java.lang.String getReferer();
    /**
     * <code>optional string referer = 9;</code>
     */
    com.google.protobuf.ByteString
        getRefererBytes();

    // optional string userAgent = 10;
    /**
     * <code>optional string userAgent = 10;</code>
     */
    boolean hasUserAgent();
    /**
     * <code>optional string userAgent = 10;</code>
     */
    java.lang.String getUserAgent();
    /**
     * <code>optional string userAgent = 10;</code>
     */
    com.google.protobuf.ByteString
        getUserAgentBytes();

    // optional string requestHost = 11;
    /**
     * <code>optional string requestHost = 11;</code>
     */
    boolean hasRequestHost();
    /**
     * <code>optional string requestHost = 11;</code>
     */
    java.lang.String getRequestHost();
    /**
     * <code>optional string requestHost = 11;</code>
     */
    com.google.protobuf.ByteString
        getRequestHostBytes();

    // optional uint64 usedTime = 12;
    /**
     * <code>optional uint64 usedTime = 12;</code>
     */
    boolean hasUsedTime();
    /**
     * <code>optional uint64 usedTime = 12;</code>
     */
    long getUsedTime();
  }
  /**
   * Protobuf type {@code ApacheLog}
   */
  public static final class ApacheLog extends
      com.google.protobuf.GeneratedMessage
      implements ApacheLogOrBuilder {
    // Use ApacheLog.newBuilder() to construct.
    private ApacheLog(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ApacheLog(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ApacheLog defaultInstance;
    public static ApacheLog getDefaultInstance() {
      return defaultInstance;
    }

    public ApacheLog getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ApacheLog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              serverIp_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              userIp_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              requestTime_ = input.readUInt64();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              requestMethod_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              requestUri_ = input.readBytes();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              urlQueryString_ = input.readBytes();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              httpCode_ = input.readUInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              responseLen_ = input.readUInt32();
              break;
            }
            case 74: {
              bitField0_ |= 0x00000100;
              referer_ = input.readBytes();
              break;
            }
            case 82: {
              bitField0_ |= 0x00000200;
              userAgent_ = input.readBytes();
              break;
            }
            case 90: {
              bitField0_ |= 0x00000400;
              requestHost_ = input.readBytes();
              break;
            }
            case 96: {
              bitField0_ |= 0x00000800;
              usedTime_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.voole.hobbit.proto.ApachelogPB.internal_static_ApacheLog_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.voole.hobbit.proto.ApachelogPB.internal_static_ApacheLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.voole.hobbit.proto.ApachelogPB.ApacheLog.class, com.voole.hobbit.proto.ApachelogPB.ApacheLog.Builder.class);
    }

    public static com.google.protobuf.Parser<ApacheLog> PARSER =
        new com.google.protobuf.AbstractParser<ApacheLog>() {
      public ApacheLog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ApacheLog(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ApacheLog> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string serverIp = 1;
    public static final int SERVERIP_FIELD_NUMBER = 1;
    private java.lang.Object serverIp_;
    /**
     * <code>optional string serverIp = 1;</code>
     */
    public boolean hasServerIp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string serverIp = 1;</code>
     */
    public java.lang.String getServerIp() {
      java.lang.Object ref = serverIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string serverIp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServerIpBytes() {
      java.lang.Object ref = serverIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string userIp = 2;
    public static final int USERIP_FIELD_NUMBER = 2;
    private java.lang.Object userIp_;
    /**
     * <code>optional string userIp = 2;</code>
     */
    public boolean hasUserIp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string userIp = 2;</code>
     */
    public java.lang.String getUserIp() {
      java.lang.Object ref = userIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userIp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userIp = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIpBytes() {
      java.lang.Object ref = userIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 requestTime = 3;
    public static final int REQUESTTIME_FIELD_NUMBER = 3;
    private long requestTime_;
    /**
     * <code>optional uint64 requestTime = 3;</code>
     */
    public boolean hasRequestTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 requestTime = 3;</code>
     */
    public long getRequestTime() {
      return requestTime_;
    }

    // optional string requestMethod = 4;
    public static final int REQUESTMETHOD_FIELD_NUMBER = 4;
    private java.lang.Object requestMethod_;
    /**
     * <code>optional string requestMethod = 4;</code>
     */
    public boolean hasRequestMethod() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string requestMethod = 4;</code>
     */
    public java.lang.String getRequestMethod() {
      java.lang.Object ref = requestMethod_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestMethod_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requestMethod = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRequestMethodBytes() {
      java.lang.Object ref = requestMethod_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestMethod_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string requestUri = 5;
    public static final int REQUESTURI_FIELD_NUMBER = 5;
    private java.lang.Object requestUri_;
    /**
     * <code>optional string requestUri = 5;</code>
     */
    public boolean hasRequestUri() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string requestUri = 5;</code>
     */
    public java.lang.String getRequestUri() {
      java.lang.Object ref = requestUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestUri_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requestUri = 5;</code>
     */
    public com.google.protobuf.ByteString
        getRequestUriBytes() {
      java.lang.Object ref = requestUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string urlQueryString = 6;
    public static final int URLQUERYSTRING_FIELD_NUMBER = 6;
    private java.lang.Object urlQueryString_;
    /**
     * <code>optional string urlQueryString = 6;</code>
     */
    public boolean hasUrlQueryString() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string urlQueryString = 6;</code>
     */
    public java.lang.String getUrlQueryString() {
      java.lang.Object ref = urlQueryString_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          urlQueryString_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string urlQueryString = 6;</code>
     */
    public com.google.protobuf.ByteString
        getUrlQueryStringBytes() {
      java.lang.Object ref = urlQueryString_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        urlQueryString_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 httpCode = 7;
    public static final int HTTPCODE_FIELD_NUMBER = 7;
    private int httpCode_;
    /**
     * <code>optional uint32 httpCode = 7;</code>
     */
    public boolean hasHttpCode() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint32 httpCode = 7;</code>
     */
    public int getHttpCode() {
      return httpCode_;
    }

    // optional uint32 responseLen = 8;
    public static final int RESPONSELEN_FIELD_NUMBER = 8;
    private int responseLen_;
    /**
     * <code>optional uint32 responseLen = 8;</code>
     */
    public boolean hasResponseLen() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint32 responseLen = 8;</code>
     */
    public int getResponseLen() {
      return responseLen_;
    }

    // optional string referer = 9;
    public static final int REFERER_FIELD_NUMBER = 9;
    private java.lang.Object referer_;
    /**
     * <code>optional string referer = 9;</code>
     */
    public boolean hasReferer() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional string referer = 9;</code>
     */
    public java.lang.String getReferer() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          referer_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string referer = 9;</code>
     */
    public com.google.protobuf.ByteString
        getRefererBytes() {
      java.lang.Object ref = referer_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        referer_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string userAgent = 10;
    public static final int USERAGENT_FIELD_NUMBER = 10;
    private java.lang.Object userAgent_;
    /**
     * <code>optional string userAgent = 10;</code>
     */
    public boolean hasUserAgent() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string userAgent = 10;</code>
     */
    public java.lang.String getUserAgent() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userAgent_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userAgent = 10;</code>
     */
    public com.google.protobuf.ByteString
        getUserAgentBytes() {
      java.lang.Object ref = userAgent_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userAgent_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string requestHost = 11;
    public static final int REQUESTHOST_FIELD_NUMBER = 11;
    private java.lang.Object requestHost_;
    /**
     * <code>optional string requestHost = 11;</code>
     */
    public boolean hasRequestHost() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional string requestHost = 11;</code>
     */
    public java.lang.String getRequestHost() {
      java.lang.Object ref = requestHost_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestHost_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requestHost = 11;</code>
     */
    public com.google.protobuf.ByteString
        getRequestHostBytes() {
      java.lang.Object ref = requestHost_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 usedTime = 12;
    public static final int USEDTIME_FIELD_NUMBER = 12;
    private long usedTime_;
    /**
     * <code>optional uint64 usedTime = 12;</code>
     */
    public boolean hasUsedTime() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>optional uint64 usedTime = 12;</code>
     */
    public long getUsedTime() {
      return usedTime_;
    }

    private void initFields() {
      serverIp_ = "";
      userIp_ = "";
      requestTime_ = 0L;
      requestMethod_ = "";
      requestUri_ = "";
      urlQueryString_ = "";
      httpCode_ = 0;
      responseLen_ = 0;
      referer_ = "";
      userAgent_ = "";
      requestHost_ = "";
      usedTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServerIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getUserIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, requestTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getRequestMethodBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getRequestUriBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getUrlQueryStringBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, httpCode_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt32(8, responseLen_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBytes(9, getRefererBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeBytes(10, getUserAgentBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBytes(11, getRequestHostBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeUInt64(12, usedTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServerIpBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getUserIpBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, requestTime_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getRequestMethodBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getRequestUriBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUrlQueryStringBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, httpCode_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, responseLen_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getRefererBytes());
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getUserAgentBytes());
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(11, getRequestHostBytes());
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(12, usedTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.voole.hobbit.proto.ApachelogPB.ApacheLog)) {
        return super.equals(obj);
      }
      com.voole.hobbit.proto.ApachelogPB.ApacheLog other = (com.voole.hobbit.proto.ApachelogPB.ApacheLog) obj;

      boolean result = true;
      result = result && (hasServerIp() == other.hasServerIp());
      if (hasServerIp()) {
        result = result && getServerIp()
            .equals(other.getServerIp());
      }
      result = result && (hasUserIp() == other.hasUserIp());
      if (hasUserIp()) {
        result = result && getUserIp()
            .equals(other.getUserIp());
      }
      result = result && (hasRequestTime() == other.hasRequestTime());
      if (hasRequestTime()) {
        result = result && (getRequestTime()
            == other.getRequestTime());
      }
      result = result && (hasRequestMethod() == other.hasRequestMethod());
      if (hasRequestMethod()) {
        result = result && getRequestMethod()
            .equals(other.getRequestMethod());
      }
      result = result && (hasRequestUri() == other.hasRequestUri());
      if (hasRequestUri()) {
        result = result && getRequestUri()
            .equals(other.getRequestUri());
      }
      result = result && (hasUrlQueryString() == other.hasUrlQueryString());
      if (hasUrlQueryString()) {
        result = result && getUrlQueryString()
            .equals(other.getUrlQueryString());
      }
      result = result && (hasHttpCode() == other.hasHttpCode());
      if (hasHttpCode()) {
        result = result && (getHttpCode()
            == other.getHttpCode());
      }
      result = result && (hasResponseLen() == other.hasResponseLen());
      if (hasResponseLen()) {
        result = result && (getResponseLen()
            == other.getResponseLen());
      }
      result = result && (hasReferer() == other.hasReferer());
      if (hasReferer()) {
        result = result && getReferer()
            .equals(other.getReferer());
      }
      result = result && (hasUserAgent() == other.hasUserAgent());
      if (hasUserAgent()) {
        result = result && getUserAgent()
            .equals(other.getUserAgent());
      }
      result = result && (hasRequestHost() == other.hasRequestHost());
      if (hasRequestHost()) {
        result = result && getRequestHost()
            .equals(other.getRequestHost());
      }
      result = result && (hasUsedTime() == other.hasUsedTime());
      if (hasUsedTime()) {
        result = result && (getUsedTime()
            == other.getUsedTime());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasServerIp()) {
        hash = (37 * hash) + SERVERIP_FIELD_NUMBER;
        hash = (53 * hash) + getServerIp().hashCode();
      }
      if (hasUserIp()) {
        hash = (37 * hash) + USERIP_FIELD_NUMBER;
        hash = (53 * hash) + getUserIp().hashCode();
      }
      if (hasRequestTime()) {
        hash = (37 * hash) + REQUESTTIME_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getRequestTime());
      }
      if (hasRequestMethod()) {
        hash = (37 * hash) + REQUESTMETHOD_FIELD_NUMBER;
        hash = (53 * hash) + getRequestMethod().hashCode();
      }
      if (hasRequestUri()) {
        hash = (37 * hash) + REQUESTURI_FIELD_NUMBER;
        hash = (53 * hash) + getRequestUri().hashCode();
      }
      if (hasUrlQueryString()) {
        hash = (37 * hash) + URLQUERYSTRING_FIELD_NUMBER;
        hash = (53 * hash) + getUrlQueryString().hashCode();
      }
      if (hasHttpCode()) {
        hash = (37 * hash) + HTTPCODE_FIELD_NUMBER;
        hash = (53 * hash) + getHttpCode();
      }
      if (hasResponseLen()) {
        hash = (37 * hash) + RESPONSELEN_FIELD_NUMBER;
        hash = (53 * hash) + getResponseLen();
      }
      if (hasReferer()) {
        hash = (37 * hash) + REFERER_FIELD_NUMBER;
        hash = (53 * hash) + getReferer().hashCode();
      }
      if (hasUserAgent()) {
        hash = (37 * hash) + USERAGENT_FIELD_NUMBER;
        hash = (53 * hash) + getUserAgent().hashCode();
      }
      if (hasRequestHost()) {
        hash = (37 * hash) + REQUESTHOST_FIELD_NUMBER;
        hash = (53 * hash) + getRequestHost().hashCode();
      }
      if (hasUsedTime()) {
        hash = (37 * hash) + USEDTIME_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getUsedTime());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.voole.hobbit.proto.ApachelogPB.ApacheLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.voole.hobbit.proto.ApachelogPB.ApacheLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.voole.hobbit.proto.ApachelogPB.ApacheLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.voole.hobbit.proto.ApachelogPB.ApacheLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.voole.hobbit.proto.ApachelogPB.ApacheLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.voole.hobbit.proto.ApachelogPB.ApacheLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.voole.hobbit.proto.ApachelogPB.ApacheLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.voole.hobbit.proto.ApachelogPB.ApacheLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.voole.hobbit.proto.ApachelogPB.ApacheLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.voole.hobbit.proto.ApachelogPB.ApacheLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.voole.hobbit.proto.ApachelogPB.ApacheLog prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ApacheLog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.voole.hobbit.proto.ApachelogPB.ApacheLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.voole.hobbit.proto.ApachelogPB.internal_static_ApacheLog_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.voole.hobbit.proto.ApachelogPB.internal_static_ApacheLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.voole.hobbit.proto.ApachelogPB.ApacheLog.class, com.voole.hobbit.proto.ApachelogPB.ApacheLog.Builder.class);
      }

      // Construct using com.voole.hobbit.proto.ApachelogPB.ApacheLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        userIp_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        requestTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        requestMethod_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        requestUri_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        urlQueryString_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        httpCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        responseLen_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        referer_ = "";
        bitField0_ = (bitField0_ & ~0x00000100);
        userAgent_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        requestHost_ = "";
        bitField0_ = (bitField0_ & ~0x00000400);
        usedTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000800);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.voole.hobbit.proto.ApachelogPB.internal_static_ApacheLog_descriptor;
      }

      public com.voole.hobbit.proto.ApachelogPB.ApacheLog getDefaultInstanceForType() {
        return com.voole.hobbit.proto.ApachelogPB.ApacheLog.getDefaultInstance();
      }

      public com.voole.hobbit.proto.ApachelogPB.ApacheLog build() {
        com.voole.hobbit.proto.ApachelogPB.ApacheLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.voole.hobbit.proto.ApachelogPB.ApacheLog buildPartial() {
        com.voole.hobbit.proto.ApachelogPB.ApacheLog result = new com.voole.hobbit.proto.ApachelogPB.ApacheLog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverIp_ = serverIp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userIp_ = userIp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.requestTime_ = requestTime_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.requestMethod_ = requestMethod_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.requestUri_ = requestUri_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.urlQueryString_ = urlQueryString_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.httpCode_ = httpCode_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.responseLen_ = responseLen_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.referer_ = referer_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.userAgent_ = userAgent_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.requestHost_ = requestHost_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.usedTime_ = usedTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.voole.hobbit.proto.ApachelogPB.ApacheLog) {
          return mergeFrom((com.voole.hobbit.proto.ApachelogPB.ApacheLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.voole.hobbit.proto.ApachelogPB.ApacheLog other) {
        if (other == com.voole.hobbit.proto.ApachelogPB.ApacheLog.getDefaultInstance()) return this;
        if (other.hasServerIp()) {
          bitField0_ |= 0x00000001;
          serverIp_ = other.serverIp_;
          onChanged();
        }
        if (other.hasUserIp()) {
          bitField0_ |= 0x00000002;
          userIp_ = other.userIp_;
          onChanged();
        }
        if (other.hasRequestTime()) {
          setRequestTime(other.getRequestTime());
        }
        if (other.hasRequestMethod()) {
          bitField0_ |= 0x00000008;
          requestMethod_ = other.requestMethod_;
          onChanged();
        }
        if (other.hasRequestUri()) {
          bitField0_ |= 0x00000010;
          requestUri_ = other.requestUri_;
          onChanged();
        }
        if (other.hasUrlQueryString()) {
          bitField0_ |= 0x00000020;
          urlQueryString_ = other.urlQueryString_;
          onChanged();
        }
        if (other.hasHttpCode()) {
          setHttpCode(other.getHttpCode());
        }
        if (other.hasResponseLen()) {
          setResponseLen(other.getResponseLen());
        }
        if (other.hasReferer()) {
          bitField0_ |= 0x00000100;
          referer_ = other.referer_;
          onChanged();
        }
        if (other.hasUserAgent()) {
          bitField0_ |= 0x00000200;
          userAgent_ = other.userAgent_;
          onChanged();
        }
        if (other.hasRequestHost()) {
          bitField0_ |= 0x00000400;
          requestHost_ = other.requestHost_;
          onChanged();
        }
        if (other.hasUsedTime()) {
          setUsedTime(other.getUsedTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.voole.hobbit.proto.ApachelogPB.ApacheLog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.voole.hobbit.proto.ApachelogPB.ApacheLog) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string serverIp = 1;
      private java.lang.Object serverIp_ = "";
      /**
       * <code>optional string serverIp = 1;</code>
       */
      public boolean hasServerIp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string serverIp = 1;</code>
       */
      public java.lang.String getServerIp() {
        java.lang.Object ref = serverIp_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          serverIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string serverIp = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServerIpBytes() {
        java.lang.Object ref = serverIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string serverIp = 1;</code>
       */
      public Builder setServerIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverIp = 1;</code>
       */
      public Builder clearServerIp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverIp_ = getDefaultInstance().getServerIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string serverIp = 1;</code>
       */
      public Builder setServerIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverIp_ = value;
        onChanged();
        return this;
      }

      // optional string userIp = 2;
      private java.lang.Object userIp_ = "";
      /**
       * <code>optional string userIp = 2;</code>
       */
      public boolean hasUserIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string userIp = 2;</code>
       */
      public java.lang.String getUserIp() {
        java.lang.Object ref = userIp_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userIp = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIpBytes() {
        java.lang.Object ref = userIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userIp = 2;</code>
       */
      public Builder setUserIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userIp = 2;</code>
       */
      public Builder clearUserIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userIp_ = getDefaultInstance().getUserIp();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userIp = 2;</code>
       */
      public Builder setUserIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userIp_ = value;
        onChanged();
        return this;
      }

      // optional uint64 requestTime = 3;
      private long requestTime_ ;
      /**
       * <code>optional uint64 requestTime = 3;</code>
       */
      public boolean hasRequestTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 requestTime = 3;</code>
       */
      public long getRequestTime() {
        return requestTime_;
      }
      /**
       * <code>optional uint64 requestTime = 3;</code>
       */
      public Builder setRequestTime(long value) {
        bitField0_ |= 0x00000004;
        requestTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 requestTime = 3;</code>
       */
      public Builder clearRequestTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        requestTime_ = 0L;
        onChanged();
        return this;
      }

      // optional string requestMethod = 4;
      private java.lang.Object requestMethod_ = "";
      /**
       * <code>optional string requestMethod = 4;</code>
       */
      public boolean hasRequestMethod() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string requestMethod = 4;</code>
       */
      public java.lang.String getRequestMethod() {
        java.lang.Object ref = requestMethod_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestMethod_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestMethod = 4;</code>
       */
      public com.google.protobuf.ByteString
          getRequestMethodBytes() {
        java.lang.Object ref = requestMethod_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestMethod_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestMethod = 4;</code>
       */
      public Builder setRequestMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        requestMethod_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestMethod = 4;</code>
       */
      public Builder clearRequestMethod() {
        bitField0_ = (bitField0_ & ~0x00000008);
        requestMethod_ = getDefaultInstance().getRequestMethod();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestMethod = 4;</code>
       */
      public Builder setRequestMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        requestMethod_ = value;
        onChanged();
        return this;
      }

      // optional string requestUri = 5;
      private java.lang.Object requestUri_ = "";
      /**
       * <code>optional string requestUri = 5;</code>
       */
      public boolean hasRequestUri() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string requestUri = 5;</code>
       */
      public java.lang.String getRequestUri() {
        java.lang.Object ref = requestUri_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestUri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestUri = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRequestUriBytes() {
        java.lang.Object ref = requestUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestUri = 5;</code>
       */
      public Builder setRequestUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        requestUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestUri = 5;</code>
       */
      public Builder clearRequestUri() {
        bitField0_ = (bitField0_ & ~0x00000010);
        requestUri_ = getDefaultInstance().getRequestUri();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestUri = 5;</code>
       */
      public Builder setRequestUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        requestUri_ = value;
        onChanged();
        return this;
      }

      // optional string urlQueryString = 6;
      private java.lang.Object urlQueryString_ = "";
      /**
       * <code>optional string urlQueryString = 6;</code>
       */
      public boolean hasUrlQueryString() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string urlQueryString = 6;</code>
       */
      public java.lang.String getUrlQueryString() {
        java.lang.Object ref = urlQueryString_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          urlQueryString_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string urlQueryString = 6;</code>
       */
      public com.google.protobuf.ByteString
          getUrlQueryStringBytes() {
        java.lang.Object ref = urlQueryString_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          urlQueryString_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string urlQueryString = 6;</code>
       */
      public Builder setUrlQueryString(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        urlQueryString_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string urlQueryString = 6;</code>
       */
      public Builder clearUrlQueryString() {
        bitField0_ = (bitField0_ & ~0x00000020);
        urlQueryString_ = getDefaultInstance().getUrlQueryString();
        onChanged();
        return this;
      }
      /**
       * <code>optional string urlQueryString = 6;</code>
       */
      public Builder setUrlQueryStringBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        urlQueryString_ = value;
        onChanged();
        return this;
      }

      // optional uint32 httpCode = 7;
      private int httpCode_ ;
      /**
       * <code>optional uint32 httpCode = 7;</code>
       */
      public boolean hasHttpCode() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint32 httpCode = 7;</code>
       */
      public int getHttpCode() {
        return httpCode_;
      }
      /**
       * <code>optional uint32 httpCode = 7;</code>
       */
      public Builder setHttpCode(int value) {
        bitField0_ |= 0x00000040;
        httpCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 httpCode = 7;</code>
       */
      public Builder clearHttpCode() {
        bitField0_ = (bitField0_ & ~0x00000040);
        httpCode_ = 0;
        onChanged();
        return this;
      }

      // optional uint32 responseLen = 8;
      private int responseLen_ ;
      /**
       * <code>optional uint32 responseLen = 8;</code>
       */
      public boolean hasResponseLen() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint32 responseLen = 8;</code>
       */
      public int getResponseLen() {
        return responseLen_;
      }
      /**
       * <code>optional uint32 responseLen = 8;</code>
       */
      public Builder setResponseLen(int value) {
        bitField0_ |= 0x00000080;
        responseLen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 responseLen = 8;</code>
       */
      public Builder clearResponseLen() {
        bitField0_ = (bitField0_ & ~0x00000080);
        responseLen_ = 0;
        onChanged();
        return this;
      }

      // optional string referer = 9;
      private java.lang.Object referer_ = "";
      /**
       * <code>optional string referer = 9;</code>
       */
      public boolean hasReferer() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional string referer = 9;</code>
       */
      public java.lang.String getReferer() {
        java.lang.Object ref = referer_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          referer_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string referer = 9;</code>
       */
      public com.google.protobuf.ByteString
          getRefererBytes() {
        java.lang.Object ref = referer_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          referer_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string referer = 9;</code>
       */
      public Builder setReferer(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        referer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string referer = 9;</code>
       */
      public Builder clearReferer() {
        bitField0_ = (bitField0_ & ~0x00000100);
        referer_ = getDefaultInstance().getReferer();
        onChanged();
        return this;
      }
      /**
       * <code>optional string referer = 9;</code>
       */
      public Builder setRefererBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000100;
        referer_ = value;
        onChanged();
        return this;
      }

      // optional string userAgent = 10;
      private java.lang.Object userAgent_ = "";
      /**
       * <code>optional string userAgent = 10;</code>
       */
      public boolean hasUserAgent() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string userAgent = 10;</code>
       */
      public java.lang.String getUserAgent() {
        java.lang.Object ref = userAgent_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          userAgent_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userAgent = 10;</code>
       */
      public com.google.protobuf.ByteString
          getUserAgentBytes() {
        java.lang.Object ref = userAgent_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userAgent_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userAgent = 10;</code>
       */
      public Builder setUserAgent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        userAgent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userAgent = 10;</code>
       */
      public Builder clearUserAgent() {
        bitField0_ = (bitField0_ & ~0x00000200);
        userAgent_ = getDefaultInstance().getUserAgent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userAgent = 10;</code>
       */
      public Builder setUserAgentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        userAgent_ = value;
        onChanged();
        return this;
      }

      // optional string requestHost = 11;
      private java.lang.Object requestHost_ = "";
      /**
       * <code>optional string requestHost = 11;</code>
       */
      public boolean hasRequestHost() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional string requestHost = 11;</code>
       */
      public java.lang.String getRequestHost() {
        java.lang.Object ref = requestHost_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          requestHost_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestHost = 11;</code>
       */
      public com.google.protobuf.ByteString
          getRequestHostBytes() {
        java.lang.Object ref = requestHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestHost = 11;</code>
       */
      public Builder setRequestHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        requestHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestHost = 11;</code>
       */
      public Builder clearRequestHost() {
        bitField0_ = (bitField0_ & ~0x00000400);
        requestHost_ = getDefaultInstance().getRequestHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestHost = 11;</code>
       */
      public Builder setRequestHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000400;
        requestHost_ = value;
        onChanged();
        return this;
      }

      // optional uint64 usedTime = 12;
      private long usedTime_ ;
      /**
       * <code>optional uint64 usedTime = 12;</code>
       */
      public boolean hasUsedTime() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>optional uint64 usedTime = 12;</code>
       */
      public long getUsedTime() {
        return usedTime_;
      }
      /**
       * <code>optional uint64 usedTime = 12;</code>
       */
      public Builder setUsedTime(long value) {
        bitField0_ |= 0x00000800;
        usedTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 usedTime = 12;</code>
       */
      public Builder clearUsedTime() {
        bitField0_ = (bitField0_ & ~0x00000800);
        usedTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ApacheLog)
    }

    static {
      defaultInstance = new ApacheLog(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ApacheLog)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ApacheLog_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ApacheLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*src/main/resources/proto/ApachelogPB.p" +
      "roto\"\367\001\n\tApacheLog\022\020\n\010serverIp\030\001 \001(\t\022\016\n\006" +
      "userIp\030\002 \001(\t\022\023\n\013requestTime\030\003 \001(\004\022\025\n\rreq" +
      "uestMethod\030\004 \001(\t\022\022\n\nrequestUri\030\005 \001(\t\022\026\n\016" +
      "urlQueryString\030\006 \001(\t\022\020\n\010httpCode\030\007 \001(\r\022\023" +
      "\n\013responseLen\030\010 \001(\r\022\017\n\007referer\030\t \001(\t\022\021\n\t" +
      "userAgent\030\n \001(\t\022\023\n\013requestHost\030\013 \001(\t\022\020\n\010" +
      "usedTime\030\014 \001(\004B\033\n\026com.voole.hobbit.proto" +
      "\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ApacheLog_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ApacheLog_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ApacheLog_descriptor,
              new java.lang.String[] { "ServerIp", "UserIp", "RequestTime", "RequestMethod", "RequestUri", "UrlQueryString", "HttpCode", "ResponseLen", "Referer", "UserAgent", "RequestHost", "UsedTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
