/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.voole.hobbit2.camus.order;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OrderPlayAliveReqV2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderPlayAliveReqV2\",\"namespace\":\"com.voole.hobbit2.camus.order\",\"fields\":[{\"name\":\"sessID\",\"type\":[\"string\",\"null\"]},{\"name\":\"aliveTick\",\"type\":[\"long\",\"null\"]},{\"name\":\"readNum\",\"type\":[\"long\",\"null\"]},{\"name\":\"unsuccRead\",\"type\":[\"long\",\"null\"]},{\"name\":\"readPos\",\"type\":[\"long\",\"null\"]},{\"name\":\"sessAvgSpeed\",\"type\":[\"long\",\"null\"]},{\"name\":\"linkNum\",\"type\":[\"int\",\"null\"]},{\"name\":\"_srvs\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OrderPlayAliveReqSrvV2\",\"fields\":[{\"name\":\"srvIP\",\"type\":[\"long\",\"null\"]},{\"name\":\"connTimes\",\"type\":[\"long\",\"null\"]},{\"name\":\"transNum\",\"type\":[\"long\",\"null\"]},{\"name\":\"avgRTT\",\"type\":[\"long\",\"null\"]},{\"name\":\"accBytes\",\"type\":[\"long\",\"null\"]},{\"name\":\"accTime\",\"type\":[\"long\",\"null\"]},{\"name\":\"avgSpeed\",\"type\":[\"long\",\"null\"]}]}}]},{\"name\":\"natip\",\"type\":[\"long\",\"null\"]},{\"name\":\"perfIp\",\"type\":[\"string\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence sessID;
  @Deprecated public java.lang.Long aliveTick;
  @Deprecated public java.lang.Long readNum;
  @Deprecated public java.lang.Long unsuccRead;
  @Deprecated public java.lang.Long readPos;
  @Deprecated public java.lang.Long sessAvgSpeed;
  @Deprecated public java.lang.Integer linkNum;
  @Deprecated public java.util.List<com.voole.hobbit2.camus.order.OrderPlayAliveReqSrvV2> _srvs;
  @Deprecated public java.lang.Long natip;
  @Deprecated public java.lang.CharSequence perfIp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public OrderPlayAliveReqV2() {}

  /**
   * All-args constructor.
   */
  public OrderPlayAliveReqV2(java.lang.CharSequence sessID, java.lang.Long aliveTick, java.lang.Long readNum, java.lang.Long unsuccRead, java.lang.Long readPos, java.lang.Long sessAvgSpeed, java.lang.Integer linkNum, java.util.List<com.voole.hobbit2.camus.order.OrderPlayAliveReqSrvV2> _srvs, java.lang.Long natip, java.lang.CharSequence perfIp) {
    this.sessID = sessID;
    this.aliveTick = aliveTick;
    this.readNum = readNum;
    this.unsuccRead = unsuccRead;
    this.readPos = readPos;
    this.sessAvgSpeed = sessAvgSpeed;
    this.linkNum = linkNum;
    this._srvs = _srvs;
    this.natip = natip;
    this.perfIp = perfIp;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sessID;
    case 1: return aliveTick;
    case 2: return readNum;
    case 3: return unsuccRead;
    case 4: return readPos;
    case 5: return sessAvgSpeed;
    case 6: return linkNum;
    case 7: return _srvs;
    case 8: return natip;
    case 9: return perfIp;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sessID = (java.lang.CharSequence)value$; break;
    case 1: aliveTick = (java.lang.Long)value$; break;
    case 2: readNum = (java.lang.Long)value$; break;
    case 3: unsuccRead = (java.lang.Long)value$; break;
    case 4: readPos = (java.lang.Long)value$; break;
    case 5: sessAvgSpeed = (java.lang.Long)value$; break;
    case 6: linkNum = (java.lang.Integer)value$; break;
    case 7: _srvs = (java.util.List<com.voole.hobbit2.camus.order.OrderPlayAliveReqSrvV2>)value$; break;
    case 8: natip = (java.lang.Long)value$; break;
    case 9: perfIp = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sessID' field.
   */
  public java.lang.CharSequence getSessID() {
    return sessID;
  }

  /**
   * Sets the value of the 'sessID' field.
   * @param value the value to set.
   */
  public void setSessID(java.lang.CharSequence value) {
    this.sessID = value;
  }

  /**
   * Gets the value of the 'aliveTick' field.
   */
  public java.lang.Long getAliveTick() {
    return aliveTick;
  }

  /**
   * Sets the value of the 'aliveTick' field.
   * @param value the value to set.
   */
  public void setAliveTick(java.lang.Long value) {
    this.aliveTick = value;
  }

  /**
   * Gets the value of the 'readNum' field.
   */
  public java.lang.Long getReadNum() {
    return readNum;
  }

  /**
   * Sets the value of the 'readNum' field.
   * @param value the value to set.
   */
  public void setReadNum(java.lang.Long value) {
    this.readNum = value;
  }

  /**
   * Gets the value of the 'unsuccRead' field.
   */
  public java.lang.Long getUnsuccRead() {
    return unsuccRead;
  }

  /**
   * Sets the value of the 'unsuccRead' field.
   * @param value the value to set.
   */
  public void setUnsuccRead(java.lang.Long value) {
    this.unsuccRead = value;
  }

  /**
   * Gets the value of the 'readPos' field.
   */
  public java.lang.Long getReadPos() {
    return readPos;
  }

  /**
   * Sets the value of the 'readPos' field.
   * @param value the value to set.
   */
  public void setReadPos(java.lang.Long value) {
    this.readPos = value;
  }

  /**
   * Gets the value of the 'sessAvgSpeed' field.
   */
  public java.lang.Long getSessAvgSpeed() {
    return sessAvgSpeed;
  }

  /**
   * Sets the value of the 'sessAvgSpeed' field.
   * @param value the value to set.
   */
  public void setSessAvgSpeed(java.lang.Long value) {
    this.sessAvgSpeed = value;
  }

  /**
   * Gets the value of the 'linkNum' field.
   */
  public java.lang.Integer getLinkNum() {
    return linkNum;
  }

  /**
   * Sets the value of the 'linkNum' field.
   * @param value the value to set.
   */
  public void setLinkNum(java.lang.Integer value) {
    this.linkNum = value;
  }

  /**
   * Gets the value of the '_srvs' field.
   */
  public java.util.List<com.voole.hobbit2.camus.order.OrderPlayAliveReqSrvV2> getSrvs$1() {
    return _srvs;
  }

  /**
   * Sets the value of the '_srvs' field.
   * @param value the value to set.
   */
  public void setSrvs$1(java.util.List<com.voole.hobbit2.camus.order.OrderPlayAliveReqSrvV2> value) {
    this._srvs = value;
  }

  /**
   * Gets the value of the 'natip' field.
   */
  public java.lang.Long getNatip() {
    return natip;
  }

  /**
   * Sets the value of the 'natip' field.
   * @param value the value to set.
   */
  public void setNatip(java.lang.Long value) {
    this.natip = value;
  }

  /**
   * Gets the value of the 'perfIp' field.
   */
  public java.lang.CharSequence getPerfIp() {
    return perfIp;
  }

  /**
   * Sets the value of the 'perfIp' field.
   * @param value the value to set.
   */
  public void setPerfIp(java.lang.CharSequence value) {
    this.perfIp = value;
  }

  /** Creates a new OrderPlayAliveReqV2 RecordBuilder */
  public static com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder newBuilder() {
    return new com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder();
  }
  
  /** Creates a new OrderPlayAliveReqV2 RecordBuilder by copying an existing Builder */
  public static com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder newBuilder(com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder other) {
    return new com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder(other);
  }
  
  /** Creates a new OrderPlayAliveReqV2 RecordBuilder by copying an existing OrderPlayAliveReqV2 instance */
  public static com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder newBuilder(com.voole.hobbit2.camus.order.OrderPlayAliveReqV2 other) {
    return new com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder(other);
  }
  
  /**
   * RecordBuilder for OrderPlayAliveReqV2 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderPlayAliveReqV2>
    implements org.apache.avro.data.RecordBuilder<OrderPlayAliveReqV2> {

    private java.lang.CharSequence sessID;
    private java.lang.Long aliveTick;
    private java.lang.Long readNum;
    private java.lang.Long unsuccRead;
    private java.lang.Long readPos;
    private java.lang.Long sessAvgSpeed;
    private java.lang.Integer linkNum;
    private java.util.List<com.voole.hobbit2.camus.order.OrderPlayAliveReqSrvV2> _srvs;
    private java.lang.Long natip;
    private java.lang.CharSequence perfIp;

    /** Creates a new Builder */
    private Builder() {
      super(com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sessID)) {
        this.sessID = data().deepCopy(fields()[0].schema(), other.sessID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.aliveTick)) {
        this.aliveTick = data().deepCopy(fields()[1].schema(), other.aliveTick);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.readNum)) {
        this.readNum = data().deepCopy(fields()[2].schema(), other.readNum);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.unsuccRead)) {
        this.unsuccRead = data().deepCopy(fields()[3].schema(), other.unsuccRead);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.readPos)) {
        this.readPos = data().deepCopy(fields()[4].schema(), other.readPos);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.sessAvgSpeed)) {
        this.sessAvgSpeed = data().deepCopy(fields()[5].schema(), other.sessAvgSpeed);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.linkNum)) {
        this.linkNum = data().deepCopy(fields()[6].schema(), other.linkNum);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other._srvs)) {
        this._srvs = data().deepCopy(fields()[7].schema(), other._srvs);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.natip)) {
        this.natip = data().deepCopy(fields()[8].schema(), other.natip);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.perfIp)) {
        this.perfIp = data().deepCopy(fields()[9].schema(), other.perfIp);
        fieldSetFlags()[9] = true;
      }
    }
    
    /** Creates a Builder by copying an existing OrderPlayAliveReqV2 instance */
    private Builder(com.voole.hobbit2.camus.order.OrderPlayAliveReqV2 other) {
            super(com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.SCHEMA$);
      if (isValidValue(fields()[0], other.sessID)) {
        this.sessID = data().deepCopy(fields()[0].schema(), other.sessID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.aliveTick)) {
        this.aliveTick = data().deepCopy(fields()[1].schema(), other.aliveTick);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.readNum)) {
        this.readNum = data().deepCopy(fields()[2].schema(), other.readNum);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.unsuccRead)) {
        this.unsuccRead = data().deepCopy(fields()[3].schema(), other.unsuccRead);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.readPos)) {
        this.readPos = data().deepCopy(fields()[4].schema(), other.readPos);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.sessAvgSpeed)) {
        this.sessAvgSpeed = data().deepCopy(fields()[5].schema(), other.sessAvgSpeed);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.linkNum)) {
        this.linkNum = data().deepCopy(fields()[6].schema(), other.linkNum);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other._srvs)) {
        this._srvs = data().deepCopy(fields()[7].schema(), other._srvs);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.natip)) {
        this.natip = data().deepCopy(fields()[8].schema(), other.natip);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.perfIp)) {
        this.perfIp = data().deepCopy(fields()[9].schema(), other.perfIp);
        fieldSetFlags()[9] = true;
      }
    }

    /** Gets the value of the 'sessID' field */
    public java.lang.CharSequence getSessID() {
      return sessID;
    }
    
    /** Sets the value of the 'sessID' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder setSessID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.sessID = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'sessID' field has been set */
    public boolean hasSessID() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'sessID' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder clearSessID() {
      sessID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'aliveTick' field */
    public java.lang.Long getAliveTick() {
      return aliveTick;
    }
    
    /** Sets the value of the 'aliveTick' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder setAliveTick(java.lang.Long value) {
      validate(fields()[1], value);
      this.aliveTick = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'aliveTick' field has been set */
    public boolean hasAliveTick() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'aliveTick' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder clearAliveTick() {
      aliveTick = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'readNum' field */
    public java.lang.Long getReadNum() {
      return readNum;
    }
    
    /** Sets the value of the 'readNum' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder setReadNum(java.lang.Long value) {
      validate(fields()[2], value);
      this.readNum = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'readNum' field has been set */
    public boolean hasReadNum() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'readNum' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder clearReadNum() {
      readNum = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'unsuccRead' field */
    public java.lang.Long getUnsuccRead() {
      return unsuccRead;
    }
    
    /** Sets the value of the 'unsuccRead' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder setUnsuccRead(java.lang.Long value) {
      validate(fields()[3], value);
      this.unsuccRead = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'unsuccRead' field has been set */
    public boolean hasUnsuccRead() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'unsuccRead' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder clearUnsuccRead() {
      unsuccRead = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'readPos' field */
    public java.lang.Long getReadPos() {
      return readPos;
    }
    
    /** Sets the value of the 'readPos' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder setReadPos(java.lang.Long value) {
      validate(fields()[4], value);
      this.readPos = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'readPos' field has been set */
    public boolean hasReadPos() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'readPos' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder clearReadPos() {
      readPos = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /** Gets the value of the 'sessAvgSpeed' field */
    public java.lang.Long getSessAvgSpeed() {
      return sessAvgSpeed;
    }
    
    /** Sets the value of the 'sessAvgSpeed' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder setSessAvgSpeed(java.lang.Long value) {
      validate(fields()[5], value);
      this.sessAvgSpeed = value;
      fieldSetFlags()[5] = true;
      return this; 
    }
    
    /** Checks whether the 'sessAvgSpeed' field has been set */
    public boolean hasSessAvgSpeed() {
      return fieldSetFlags()[5];
    }
    
    /** Clears the value of the 'sessAvgSpeed' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder clearSessAvgSpeed() {
      sessAvgSpeed = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /** Gets the value of the 'linkNum' field */
    public java.lang.Integer getLinkNum() {
      return linkNum;
    }
    
    /** Sets the value of the 'linkNum' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder setLinkNum(java.lang.Integer value) {
      validate(fields()[6], value);
      this.linkNum = value;
      fieldSetFlags()[6] = true;
      return this; 
    }
    
    /** Checks whether the 'linkNum' field has been set */
    public boolean hasLinkNum() {
      return fieldSetFlags()[6];
    }
    
    /** Clears the value of the 'linkNum' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder clearLinkNum() {
      linkNum = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /** Gets the value of the '_srvs' field */
    public java.util.List<com.voole.hobbit2.camus.order.OrderPlayAliveReqSrvV2> getSrvs$1() {
      return _srvs;
    }
    
    /** Sets the value of the '_srvs' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder setSrvs$1(java.util.List<com.voole.hobbit2.camus.order.OrderPlayAliveReqSrvV2> value) {
      validate(fields()[7], value);
      this._srvs = value;
      fieldSetFlags()[7] = true;
      return this; 
    }
    
    /** Checks whether the '_srvs' field has been set */
    public boolean hasSrvs$1() {
      return fieldSetFlags()[7];
    }
    
    /** Clears the value of the '_srvs' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder clearSrvs$1() {
      _srvs = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /** Gets the value of the 'natip' field */
    public java.lang.Long getNatip() {
      return natip;
    }
    
    /** Sets the value of the 'natip' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder setNatip(java.lang.Long value) {
      validate(fields()[8], value);
      this.natip = value;
      fieldSetFlags()[8] = true;
      return this; 
    }
    
    /** Checks whether the 'natip' field has been set */
    public boolean hasNatip() {
      return fieldSetFlags()[8];
    }
    
    /** Clears the value of the 'natip' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder clearNatip() {
      natip = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /** Gets the value of the 'perfIp' field */
    public java.lang.CharSequence getPerfIp() {
      return perfIp;
    }
    
    /** Sets the value of the 'perfIp' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder setPerfIp(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.perfIp = value;
      fieldSetFlags()[9] = true;
      return this; 
    }
    
    /** Checks whether the 'perfIp' field has been set */
    public boolean hasPerfIp() {
      return fieldSetFlags()[9];
    }
    
    /** Clears the value of the 'perfIp' field */
    public com.voole.hobbit2.camus.order.OrderPlayAliveReqV2.Builder clearPerfIp() {
      perfIp = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    public OrderPlayAliveReqV2 build() {
      try {
        OrderPlayAliveReqV2 record = new OrderPlayAliveReqV2();
        record.sessID = fieldSetFlags()[0] ? this.sessID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.aliveTick = fieldSetFlags()[1] ? this.aliveTick : (java.lang.Long) defaultValue(fields()[1]);
        record.readNum = fieldSetFlags()[2] ? this.readNum : (java.lang.Long) defaultValue(fields()[2]);
        record.unsuccRead = fieldSetFlags()[3] ? this.unsuccRead : (java.lang.Long) defaultValue(fields()[3]);
        record.readPos = fieldSetFlags()[4] ? this.readPos : (java.lang.Long) defaultValue(fields()[4]);
        record.sessAvgSpeed = fieldSetFlags()[5] ? this.sessAvgSpeed : (java.lang.Long) defaultValue(fields()[5]);
        record.linkNum = fieldSetFlags()[6] ? this.linkNum : (java.lang.Integer) defaultValue(fields()[6]);
        record._srvs = fieldSetFlags()[7] ? this._srvs : (java.util.List<com.voole.hobbit2.camus.order.OrderPlayAliveReqSrvV2>) defaultValue(fields()[7]);
        record.natip = fieldSetFlags()[8] ? this.natip : (java.lang.Long) defaultValue(fields()[8]);
        record.perfIp = fieldSetFlags()[9] ? this.perfIp : (java.lang.CharSequence) defaultValue(fields()[9]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
