// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/proto/simple/TermialSimplePB.proto

package com.voole.hobbit.proto.simple;

public final class TermialSimplePB {
  private TermialSimplePB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OrderPlayBgnSimpleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint64 OEMID = 1;
    /**
     * <code>optional uint64 OEMID = 1;</code>
     */
    boolean hasOEMID();
    /**
     * <code>optional uint64 OEMID = 1;</code>
     */
    long getOEMID();

    // optional string HID = 2;
    /**
     * <code>optional string HID = 2;</code>
     */
    boolean hasHID();
    /**
     * <code>optional string HID = 2;</code>
     */
    java.lang.String getHID();
    /**
     * <code>optional string HID = 2;</code>
     */
    com.google.protobuf.ByteString
        getHIDBytes();

    // optional string sessID = 3;
    /**
     * <code>optional string sessID = 3;</code>
     */
    boolean hasSessID();
    /**
     * <code>optional string sessID = 3;</code>
     */
    java.lang.String getSessID();
    /**
     * <code>optional string sessID = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessIDBytes();

    // optional string FID = 4;
    /**
     * <code>optional string FID = 4;</code>
     */
    boolean hasFID();
    /**
     * <code>optional string FID = 4;</code>
     */
    java.lang.String getFID();
    /**
     * <code>optional string FID = 4;</code>
     */
    com.google.protobuf.ByteString
        getFIDBytes();

    // optional string URL = 5;
    /**
     * <code>optional string URL = 5;</code>
     */
    boolean hasURL();
    /**
     * <code>optional string URL = 5;</code>
     */
    java.lang.String getURL();
    /**
     * <code>optional string URL = 5;</code>
     */
    com.google.protobuf.ByteString
        getURLBytes();

    // optional uint64 stamp = 6;
    /**
     * <code>optional uint64 stamp = 6;</code>
     */
    boolean hasStamp();
    /**
     * <code>optional uint64 stamp = 6;</code>
     */
    long getStamp();
  }
  /**
   * Protobuf type {@code OrderPlayBgnSimple}
   */
  public static final class OrderPlayBgnSimple extends
      com.google.protobuf.GeneratedMessage
      implements OrderPlayBgnSimpleOrBuilder {
    // Use OrderPlayBgnSimple.newBuilder() to construct.
    private OrderPlayBgnSimple(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OrderPlayBgnSimple(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OrderPlayBgnSimple defaultInstance;
    public static OrderPlayBgnSimple getDefaultInstance() {
      return defaultInstance;
    }

    public OrderPlayBgnSimple getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OrderPlayBgnSimple(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              oEMID_ = input.readUInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              hID_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              sessID_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              fID_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              uRL_ = input.readBytes();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              stamp_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayBgnSimple_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayBgnSimple_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple.class, com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple.Builder.class);
    }

    public static com.google.protobuf.Parser<OrderPlayBgnSimple> PARSER =
        new com.google.protobuf.AbstractParser<OrderPlayBgnSimple>() {
      public OrderPlayBgnSimple parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderPlayBgnSimple(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OrderPlayBgnSimple> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint64 OEMID = 1;
    public static final int OEMID_FIELD_NUMBER = 1;
    private long oEMID_;
    /**
     * <code>optional uint64 OEMID = 1;</code>
     */
    public boolean hasOEMID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 OEMID = 1;</code>
     */
    public long getOEMID() {
      return oEMID_;
    }

    // optional string HID = 2;
    public static final int HID_FIELD_NUMBER = 2;
    private java.lang.Object hID_;
    /**
     * <code>optional string HID = 2;</code>
     */
    public boolean hasHID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string HID = 2;</code>
     */
    public java.lang.String getHID() {
      java.lang.Object ref = hID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string HID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHIDBytes() {
      java.lang.Object ref = hID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string sessID = 3;
    public static final int SESSID_FIELD_NUMBER = 3;
    private java.lang.Object sessID_;
    /**
     * <code>optional string sessID = 3;</code>
     */
    public boolean hasSessID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string sessID = 3;</code>
     */
    public java.lang.String getSessID() {
      java.lang.Object ref = sessID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sessID = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessIDBytes() {
      java.lang.Object ref = sessID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string FID = 4;
    public static final int FID_FIELD_NUMBER = 4;
    private java.lang.Object fID_;
    /**
     * <code>optional string FID = 4;</code>
     */
    public boolean hasFID() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string FID = 4;</code>
     */
    public java.lang.String getFID() {
      java.lang.Object ref = fID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          fID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string FID = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFIDBytes() {
      java.lang.Object ref = fID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string URL = 5;
    public static final int URL_FIELD_NUMBER = 5;
    private java.lang.Object uRL_;
    /**
     * <code>optional string URL = 5;</code>
     */
    public boolean hasURL() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string URL = 5;</code>
     */
    public java.lang.String getURL() {
      java.lang.Object ref = uRL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uRL_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string URL = 5;</code>
     */
    public com.google.protobuf.ByteString
        getURLBytes() {
      java.lang.Object ref = uRL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uRL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 stamp = 6;
    public static final int STAMP_FIELD_NUMBER = 6;
    private long stamp_;
    /**
     * <code>optional uint64 stamp = 6;</code>
     */
    public boolean hasStamp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint64 stamp = 6;</code>
     */
    public long getStamp() {
      return stamp_;
    }

    private void initFields() {
      oEMID_ = 0L;
      hID_ = "";
      sessID_ = "";
      fID_ = "";
      uRL_ = "";
      stamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, oEMID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getHIDBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSessIDBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getFIDBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getURLBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(6, stamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, oEMID_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getHIDBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSessIDBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getFIDBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getURLBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, stamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple)) {
        return super.equals(obj);
      }
      com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple other = (com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple) obj;

      boolean result = true;
      result = result && (hasOEMID() == other.hasOEMID());
      if (hasOEMID()) {
        result = result && (getOEMID()
            == other.getOEMID());
      }
      result = result && (hasHID() == other.hasHID());
      if (hasHID()) {
        result = result && getHID()
            .equals(other.getHID());
      }
      result = result && (hasSessID() == other.hasSessID());
      if (hasSessID()) {
        result = result && getSessID()
            .equals(other.getSessID());
      }
      result = result && (hasFID() == other.hasFID());
      if (hasFID()) {
        result = result && getFID()
            .equals(other.getFID());
      }
      result = result && (hasURL() == other.hasURL());
      if (hasURL()) {
        result = result && getURL()
            .equals(other.getURL());
      }
      result = result && (hasStamp() == other.hasStamp());
      if (hasStamp()) {
        result = result && (getStamp()
            == other.getStamp());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasOEMID()) {
        hash = (37 * hash) + OEMID_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getOEMID());
      }
      if (hasHID()) {
        hash = (37 * hash) + HID_FIELD_NUMBER;
        hash = (53 * hash) + getHID().hashCode();
      }
      if (hasSessID()) {
        hash = (37 * hash) + SESSID_FIELD_NUMBER;
        hash = (53 * hash) + getSessID().hashCode();
      }
      if (hasFID()) {
        hash = (37 * hash) + FID_FIELD_NUMBER;
        hash = (53 * hash) + getFID().hashCode();
      }
      if (hasURL()) {
        hash = (37 * hash) + URL_FIELD_NUMBER;
        hash = (53 * hash) + getURL().hashCode();
      }
      if (hasStamp()) {
        hash = (37 * hash) + STAMP_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getStamp());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderPlayBgnSimple}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimpleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayBgnSimple_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayBgnSimple_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple.class, com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple.Builder.class);
      }

      // Construct using com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        oEMID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        hID_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sessID_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        fID_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        uRL_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        stamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayBgnSimple_descriptor;
      }

      public com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple getDefaultInstanceForType() {
        return com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple.getDefaultInstance();
      }

      public com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple build() {
        com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple buildPartial() {
        com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple result = new com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.oEMID_ = oEMID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hID_ = hID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessID_ = sessID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fID_ = fID_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.uRL_ = uRL_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.stamp_ = stamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple) {
          return mergeFrom((com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple other) {
        if (other == com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple.getDefaultInstance()) return this;
        if (other.hasOEMID()) {
          setOEMID(other.getOEMID());
        }
        if (other.hasHID()) {
          bitField0_ |= 0x00000002;
          hID_ = other.hID_;
          onChanged();
        }
        if (other.hasSessID()) {
          bitField0_ |= 0x00000004;
          sessID_ = other.sessID_;
          onChanged();
        }
        if (other.hasFID()) {
          bitField0_ |= 0x00000008;
          fID_ = other.fID_;
          onChanged();
        }
        if (other.hasURL()) {
          bitField0_ |= 0x00000010;
          uRL_ = other.uRL_;
          onChanged();
        }
        if (other.hasStamp()) {
          setStamp(other.getStamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayBgnSimple) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint64 OEMID = 1;
      private long oEMID_ ;
      /**
       * <code>optional uint64 OEMID = 1;</code>
       */
      public boolean hasOEMID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 OEMID = 1;</code>
       */
      public long getOEMID() {
        return oEMID_;
      }
      /**
       * <code>optional uint64 OEMID = 1;</code>
       */
      public Builder setOEMID(long value) {
        bitField0_ |= 0x00000001;
        oEMID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 OEMID = 1;</code>
       */
      public Builder clearOEMID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        oEMID_ = 0L;
        onChanged();
        return this;
      }

      // optional string HID = 2;
      private java.lang.Object hID_ = "";
      /**
       * <code>optional string HID = 2;</code>
       */
      public boolean hasHID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string HID = 2;</code>
       */
      public java.lang.String getHID() {
        java.lang.Object ref = hID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          hID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string HID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHIDBytes() {
        java.lang.Object ref = hID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string HID = 2;</code>
       */
      public Builder setHID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        hID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string HID = 2;</code>
       */
      public Builder clearHID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hID_ = getDefaultInstance().getHID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string HID = 2;</code>
       */
      public Builder setHIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        hID_ = value;
        onChanged();
        return this;
      }

      // optional string sessID = 3;
      private java.lang.Object sessID_ = "";
      /**
       * <code>optional string sessID = 3;</code>
       */
      public boolean hasSessID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string sessID = 3;</code>
       */
      public java.lang.String getSessID() {
        java.lang.Object ref = sessID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sessID = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessIDBytes() {
        java.lang.Object ref = sessID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessID = 3;</code>
       */
      public Builder setSessID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessID = 3;</code>
       */
      public Builder clearSessID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessID_ = getDefaultInstance().getSessID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessID = 3;</code>
       */
      public Builder setSessIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessID_ = value;
        onChanged();
        return this;
      }

      // optional string FID = 4;
      private java.lang.Object fID_ = "";
      /**
       * <code>optional string FID = 4;</code>
       */
      public boolean hasFID() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string FID = 4;</code>
       */
      public java.lang.String getFID() {
        java.lang.Object ref = fID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          fID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string FID = 4;</code>
       */
      public com.google.protobuf.ByteString
          getFIDBytes() {
        java.lang.Object ref = fID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string FID = 4;</code>
       */
      public Builder setFID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string FID = 4;</code>
       */
      public Builder clearFID() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fID_ = getDefaultInstance().getFID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string FID = 4;</code>
       */
      public Builder setFIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        fID_ = value;
        onChanged();
        return this;
      }

      // optional string URL = 5;
      private java.lang.Object uRL_ = "";
      /**
       * <code>optional string URL = 5;</code>
       */
      public boolean hasURL() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string URL = 5;</code>
       */
      public java.lang.String getURL() {
        java.lang.Object ref = uRL_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          uRL_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string URL = 5;</code>
       */
      public com.google.protobuf.ByteString
          getURLBytes() {
        java.lang.Object ref = uRL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uRL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string URL = 5;</code>
       */
      public Builder setURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        uRL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string URL = 5;</code>
       */
      public Builder clearURL() {
        bitField0_ = (bitField0_ & ~0x00000010);
        uRL_ = getDefaultInstance().getURL();
        onChanged();
        return this;
      }
      /**
       * <code>optional string URL = 5;</code>
       */
      public Builder setURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        uRL_ = value;
        onChanged();
        return this;
      }

      // optional uint64 stamp = 6;
      private long stamp_ ;
      /**
       * <code>optional uint64 stamp = 6;</code>
       */
      public boolean hasStamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint64 stamp = 6;</code>
       */
      public long getStamp() {
        return stamp_;
      }
      /**
       * <code>optional uint64 stamp = 6;</code>
       */
      public Builder setStamp(long value) {
        bitField0_ |= 0x00000020;
        stamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 stamp = 6;</code>
       */
      public Builder clearStamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        stamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OrderPlayBgnSimple)
    }

    static {
      defaultInstance = new OrderPlayBgnSimple(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OrderPlayBgnSimple)
  }

  public interface OrderPlayEndSimpleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string HID = 1;
    /**
     * <code>optional string HID = 1;</code>
     */
    boolean hasHID();
    /**
     * <code>optional string HID = 1;</code>
     */
    java.lang.String getHID();
    /**
     * <code>optional string HID = 1;</code>
     */
    com.google.protobuf.ByteString
        getHIDBytes();

    // optional string sessID = 2;
    /**
     * <code>optional string sessID = 2;</code>
     */
    boolean hasSessID();
    /**
     * <code>optional string sessID = 2;</code>
     */
    java.lang.String getSessID();
    /**
     * <code>optional string sessID = 2;</code>
     */
    com.google.protobuf.ByteString
        getSessIDBytes();

    // optional uint64 stamp = 3;
    /**
     * <code>optional uint64 stamp = 3;</code>
     */
    boolean hasStamp();
    /**
     * <code>optional uint64 stamp = 3;</code>
     */
    long getStamp();

    // optional uint64 sessAvgSpeed = 4;
    /**
     * <code>optional uint64 sessAvgSpeed = 4;</code>
     */
    boolean hasSessAvgSpeed();
    /**
     * <code>optional uint64 sessAvgSpeed = 4;</code>
     */
    long getSessAvgSpeed();
  }
  /**
   * Protobuf type {@code OrderPlayEndSimple}
   */
  public static final class OrderPlayEndSimple extends
      com.google.protobuf.GeneratedMessage
      implements OrderPlayEndSimpleOrBuilder {
    // Use OrderPlayEndSimple.newBuilder() to construct.
    private OrderPlayEndSimple(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OrderPlayEndSimple(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OrderPlayEndSimple defaultInstance;
    public static OrderPlayEndSimple getDefaultInstance() {
      return defaultInstance;
    }

    public OrderPlayEndSimple getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OrderPlayEndSimple(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              hID_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              sessID_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              stamp_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              sessAvgSpeed_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayEndSimple_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayEndSimple_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple.class, com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple.Builder.class);
    }

    public static com.google.protobuf.Parser<OrderPlayEndSimple> PARSER =
        new com.google.protobuf.AbstractParser<OrderPlayEndSimple>() {
      public OrderPlayEndSimple parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderPlayEndSimple(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OrderPlayEndSimple> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string HID = 1;
    public static final int HID_FIELD_NUMBER = 1;
    private java.lang.Object hID_;
    /**
     * <code>optional string HID = 1;</code>
     */
    public boolean hasHID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string HID = 1;</code>
     */
    public java.lang.String getHID() {
      java.lang.Object ref = hID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string HID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHIDBytes() {
      java.lang.Object ref = hID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string sessID = 2;
    public static final int SESSID_FIELD_NUMBER = 2;
    private java.lang.Object sessID_;
    /**
     * <code>optional string sessID = 2;</code>
     */
    public boolean hasSessID() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string sessID = 2;</code>
     */
    public java.lang.String getSessID() {
      java.lang.Object ref = sessID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sessID = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSessIDBytes() {
      java.lang.Object ref = sessID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 stamp = 3;
    public static final int STAMP_FIELD_NUMBER = 3;
    private long stamp_;
    /**
     * <code>optional uint64 stamp = 3;</code>
     */
    public boolean hasStamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 stamp = 3;</code>
     */
    public long getStamp() {
      return stamp_;
    }

    // optional uint64 sessAvgSpeed = 4;
    public static final int SESSAVGSPEED_FIELD_NUMBER = 4;
    private long sessAvgSpeed_;
    /**
     * <code>optional uint64 sessAvgSpeed = 4;</code>
     */
    public boolean hasSessAvgSpeed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 sessAvgSpeed = 4;</code>
     */
    public long getSessAvgSpeed() {
      return sessAvgSpeed_;
    }

    private void initFields() {
      hID_ = "";
      sessID_ = "";
      stamp_ = 0L;
      sessAvgSpeed_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSessIDBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, stamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, sessAvgSpeed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSessIDBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, stamp_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, sessAvgSpeed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple)) {
        return super.equals(obj);
      }
      com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple other = (com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple) obj;

      boolean result = true;
      result = result && (hasHID() == other.hasHID());
      if (hasHID()) {
        result = result && getHID()
            .equals(other.getHID());
      }
      result = result && (hasSessID() == other.hasSessID());
      if (hasSessID()) {
        result = result && getSessID()
            .equals(other.getSessID());
      }
      result = result && (hasStamp() == other.hasStamp());
      if (hasStamp()) {
        result = result && (getStamp()
            == other.getStamp());
      }
      result = result && (hasSessAvgSpeed() == other.hasSessAvgSpeed());
      if (hasSessAvgSpeed()) {
        result = result && (getSessAvgSpeed()
            == other.getSessAvgSpeed());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasHID()) {
        hash = (37 * hash) + HID_FIELD_NUMBER;
        hash = (53 * hash) + getHID().hashCode();
      }
      if (hasSessID()) {
        hash = (37 * hash) + SESSID_FIELD_NUMBER;
        hash = (53 * hash) + getSessID().hashCode();
      }
      if (hasStamp()) {
        hash = (37 * hash) + STAMP_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getStamp());
      }
      if (hasSessAvgSpeed()) {
        hash = (37 * hash) + SESSAVGSPEED_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getSessAvgSpeed());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderPlayEndSimple}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimpleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayEndSimple_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayEndSimple_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple.class, com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple.Builder.class);
      }

      // Construct using com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        hID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sessID_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        stamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        sessAvgSpeed_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayEndSimple_descriptor;
      }

      public com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple getDefaultInstanceForType() {
        return com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple.getDefaultInstance();
      }

      public com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple build() {
        com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple buildPartial() {
        com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple result = new com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.hID_ = hID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sessID_ = sessID_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stamp_ = stamp_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sessAvgSpeed_ = sessAvgSpeed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple) {
          return mergeFrom((com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple other) {
        if (other == com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple.getDefaultInstance()) return this;
        if (other.hasHID()) {
          bitField0_ |= 0x00000001;
          hID_ = other.hID_;
          onChanged();
        }
        if (other.hasSessID()) {
          bitField0_ |= 0x00000002;
          sessID_ = other.sessID_;
          onChanged();
        }
        if (other.hasStamp()) {
          setStamp(other.getStamp());
        }
        if (other.hasSessAvgSpeed()) {
          setSessAvgSpeed(other.getSessAvgSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayEndSimple) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string HID = 1;
      private java.lang.Object hID_ = "";
      /**
       * <code>optional string HID = 1;</code>
       */
      public boolean hasHID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string HID = 1;</code>
       */
      public java.lang.String getHID() {
        java.lang.Object ref = hID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          hID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string HID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHIDBytes() {
        java.lang.Object ref = hID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string HID = 1;</code>
       */
      public Builder setHID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string HID = 1;</code>
       */
      public Builder clearHID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        hID_ = getDefaultInstance().getHID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string HID = 1;</code>
       */
      public Builder setHIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        hID_ = value;
        onChanged();
        return this;
      }

      // optional string sessID = 2;
      private java.lang.Object sessID_ = "";
      /**
       * <code>optional string sessID = 2;</code>
       */
      public boolean hasSessID() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string sessID = 2;</code>
       */
      public java.lang.String getSessID() {
        java.lang.Object ref = sessID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sessID = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSessIDBytes() {
        java.lang.Object ref = sessID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessID = 2;</code>
       */
      public Builder setSessID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessID = 2;</code>
       */
      public Builder clearSessID() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sessID_ = getDefaultInstance().getSessID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessID = 2;</code>
       */
      public Builder setSessIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sessID_ = value;
        onChanged();
        return this;
      }

      // optional uint64 stamp = 3;
      private long stamp_ ;
      /**
       * <code>optional uint64 stamp = 3;</code>
       */
      public boolean hasStamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 stamp = 3;</code>
       */
      public long getStamp() {
        return stamp_;
      }
      /**
       * <code>optional uint64 stamp = 3;</code>
       */
      public Builder setStamp(long value) {
        bitField0_ |= 0x00000004;
        stamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 stamp = 3;</code>
       */
      public Builder clearStamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stamp_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 sessAvgSpeed = 4;
      private long sessAvgSpeed_ ;
      /**
       * <code>optional uint64 sessAvgSpeed = 4;</code>
       */
      public boolean hasSessAvgSpeed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 sessAvgSpeed = 4;</code>
       */
      public long getSessAvgSpeed() {
        return sessAvgSpeed_;
      }
      /**
       * <code>optional uint64 sessAvgSpeed = 4;</code>
       */
      public Builder setSessAvgSpeed(long value) {
        bitField0_ |= 0x00000008;
        sessAvgSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sessAvgSpeed = 4;</code>
       */
      public Builder clearSessAvgSpeed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sessAvgSpeed_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OrderPlayEndSimple)
    }

    static {
      defaultInstance = new OrderPlayEndSimple(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OrderPlayEndSimple)
  }

  public interface OrderPlayAliveSimpleOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string sessID = 1;
    /**
     * <code>optional string sessID = 1;</code>
     */
    boolean hasSessID();
    /**
     * <code>optional string sessID = 1;</code>
     */
    java.lang.String getSessID();
    /**
     * <code>optional string sessID = 1;</code>
     */
    com.google.protobuf.ByteString
        getSessIDBytes();

    // optional uint64 stamp = 2;
    /**
     * <code>optional uint64 stamp = 2;</code>
     */
    boolean hasStamp();
    /**
     * <code>optional uint64 stamp = 2;</code>
     */
    long getStamp();

    // optional uint64 sessAvgSpeed = 3;
    /**
     * <code>optional uint64 sessAvgSpeed = 3;</code>
     */
    boolean hasSessAvgSpeed();
    /**
     * <code>optional uint64 sessAvgSpeed = 3;</code>
     */
    long getSessAvgSpeed();
  }
  /**
   * Protobuf type {@code OrderPlayAliveSimple}
   */
  public static final class OrderPlayAliveSimple extends
      com.google.protobuf.GeneratedMessage
      implements OrderPlayAliveSimpleOrBuilder {
    // Use OrderPlayAliveSimple.newBuilder() to construct.
    private OrderPlayAliveSimple(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OrderPlayAliveSimple(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OrderPlayAliveSimple defaultInstance;
    public static OrderPlayAliveSimple getDefaultInstance() {
      return defaultInstance;
    }

    public OrderPlayAliveSimple getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OrderPlayAliveSimple(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              sessID_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              stamp_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sessAvgSpeed_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayAliveSimple_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayAliveSimple_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple.class, com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple.Builder.class);
    }

    public static com.google.protobuf.Parser<OrderPlayAliveSimple> PARSER =
        new com.google.protobuf.AbstractParser<OrderPlayAliveSimple>() {
      public OrderPlayAliveSimple parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OrderPlayAliveSimple(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OrderPlayAliveSimple> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string sessID = 1;
    public static final int SESSID_FIELD_NUMBER = 1;
    private java.lang.Object sessID_;
    /**
     * <code>optional string sessID = 1;</code>
     */
    public boolean hasSessID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string sessID = 1;</code>
     */
    public java.lang.String getSessID() {
      java.lang.Object ref = sessID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sessID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSessIDBytes() {
      java.lang.Object ref = sessID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint64 stamp = 2;
    public static final int STAMP_FIELD_NUMBER = 2;
    private long stamp_;
    /**
     * <code>optional uint64 stamp = 2;</code>
     */
    public boolean hasStamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint64 stamp = 2;</code>
     */
    public long getStamp() {
      return stamp_;
    }

    // optional uint64 sessAvgSpeed = 3;
    public static final int SESSAVGSPEED_FIELD_NUMBER = 3;
    private long sessAvgSpeed_;
    /**
     * <code>optional uint64 sessAvgSpeed = 3;</code>
     */
    public boolean hasSessAvgSpeed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 sessAvgSpeed = 3;</code>
     */
    public long getSessAvgSpeed() {
      return sessAvgSpeed_;
    }

    private void initFields() {
      sessID_ = "";
      stamp_ = 0L;
      sessAvgSpeed_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getSessIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, stamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, sessAvgSpeed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getSessIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, stamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, sessAvgSpeed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple)) {
        return super.equals(obj);
      }
      com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple other = (com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple) obj;

      boolean result = true;
      result = result && (hasSessID() == other.hasSessID());
      if (hasSessID()) {
        result = result && getSessID()
            .equals(other.getSessID());
      }
      result = result && (hasStamp() == other.hasStamp());
      if (hasStamp()) {
        result = result && (getStamp()
            == other.getStamp());
      }
      result = result && (hasSessAvgSpeed() == other.hasSessAvgSpeed());
      if (hasSessAvgSpeed()) {
        result = result && (getSessAvgSpeed()
            == other.getSessAvgSpeed());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }

    private int memoizedHashCode = 0;
    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasSessID()) {
        hash = (37 * hash) + SESSID_FIELD_NUMBER;
        hash = (53 * hash) + getSessID().hashCode();
      }
      if (hasStamp()) {
        hash = (37 * hash) + STAMP_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getStamp());
      }
      if (hasSessAvgSpeed()) {
        hash = (37 * hash) + SESSAVGSPEED_FIELD_NUMBER;
        hash = (53 * hash) + hashLong(getSessAvgSpeed());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code OrderPlayAliveSimple}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimpleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayAliveSimple_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayAliveSimple_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple.class, com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple.Builder.class);
      }

      // Construct using com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        sessID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        stamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        sessAvgSpeed_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.voole.hobbit.proto.simple.TermialSimplePB.internal_static_OrderPlayAliveSimple_descriptor;
      }

      public com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple getDefaultInstanceForType() {
        return com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple.getDefaultInstance();
      }

      public com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple build() {
        com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple buildPartial() {
        com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple result = new com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.sessID_ = sessID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stamp_ = stamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessAvgSpeed_ = sessAvgSpeed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple) {
          return mergeFrom((com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple other) {
        if (other == com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple.getDefaultInstance()) return this;
        if (other.hasSessID()) {
          bitField0_ |= 0x00000001;
          sessID_ = other.sessID_;
          onChanged();
        }
        if (other.hasStamp()) {
          setStamp(other.getStamp());
        }
        if (other.hasSessAvgSpeed()) {
          setSessAvgSpeed(other.getSessAvgSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.voole.hobbit.proto.simple.TermialSimplePB.OrderPlayAliveSimple) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string sessID = 1;
      private java.lang.Object sessID_ = "";
      /**
       * <code>optional string sessID = 1;</code>
       */
      public boolean hasSessID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string sessID = 1;</code>
       */
      public java.lang.String getSessID() {
        java.lang.Object ref = sessID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sessID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSessIDBytes() {
        java.lang.Object ref = sessID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessID = 1;</code>
       */
      public Builder setSessID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sessID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessID = 1;</code>
       */
      public Builder clearSessID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        sessID_ = getDefaultInstance().getSessID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessID = 1;</code>
       */
      public Builder setSessIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        sessID_ = value;
        onChanged();
        return this;
      }

      // optional uint64 stamp = 2;
      private long stamp_ ;
      /**
       * <code>optional uint64 stamp = 2;</code>
       */
      public boolean hasStamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint64 stamp = 2;</code>
       */
      public long getStamp() {
        return stamp_;
      }
      /**
       * <code>optional uint64 stamp = 2;</code>
       */
      public Builder setStamp(long value) {
        bitField0_ |= 0x00000002;
        stamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 stamp = 2;</code>
       */
      public Builder clearStamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stamp_ = 0L;
        onChanged();
        return this;
      }

      // optional uint64 sessAvgSpeed = 3;
      private long sessAvgSpeed_ ;
      /**
       * <code>optional uint64 sessAvgSpeed = 3;</code>
       */
      public boolean hasSessAvgSpeed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 sessAvgSpeed = 3;</code>
       */
      public long getSessAvgSpeed() {
        return sessAvgSpeed_;
      }
      /**
       * <code>optional uint64 sessAvgSpeed = 3;</code>
       */
      public Builder setSessAvgSpeed(long value) {
        bitField0_ |= 0x00000004;
        sessAvgSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 sessAvgSpeed = 3;</code>
       */
      public Builder clearSessAvgSpeed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessAvgSpeed_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:OrderPlayAliveSimple)
    }

    static {
      defaultInstance = new OrderPlayAliveSimple(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:OrderPlayAliveSimple)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderPlayBgnSimple_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OrderPlayBgnSimple_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderPlayEndSimple_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OrderPlayEndSimple_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_OrderPlayAliveSimple_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_OrderPlayAliveSimple_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5src/main/resources/proto/simple/Termia" +
      "lSimplePB.proto\"i\n\022OrderPlayBgnSimple\022\r\n" +
      "\005OEMID\030\001 \001(\004\022\013\n\003HID\030\002 \001(\t\022\016\n\006sessID\030\003 \001(" +
      "\t\022\013\n\003FID\030\004 \001(\t\022\013\n\003URL\030\005 \001(\t\022\r\n\005stamp\030\006 \001" +
      "(\004\"V\n\022OrderPlayEndSimple\022\013\n\003HID\030\001 \001(\t\022\016\n" +
      "\006sessID\030\002 \001(\t\022\r\n\005stamp\030\003 \001(\004\022\024\n\014sessAvgS" +
      "peed\030\004 \001(\004\"K\n\024OrderPlayAliveSimple\022\016\n\006se" +
      "ssID\030\001 \001(\t\022\r\n\005stamp\030\002 \001(\004\022\024\n\014sessAvgSpee" +
      "d\030\003 \001(\004B\"\n\035com.voole.hobbit.proto.simple" +
      "\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_OrderPlayBgnSimple_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_OrderPlayBgnSimple_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OrderPlayBgnSimple_descriptor,
              new java.lang.String[] { "OEMID", "HID", "SessID", "FID", "URL", "Stamp", });
          internal_static_OrderPlayEndSimple_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_OrderPlayEndSimple_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OrderPlayEndSimple_descriptor,
              new java.lang.String[] { "HID", "SessID", "Stamp", "SessAvgSpeed", });
          internal_static_OrderPlayAliveSimple_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_OrderPlayAliveSimple_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_OrderPlayAliveSimple_descriptor,
              new java.lang.String[] { "SessID", "Stamp", "SessAvgSpeed", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
