/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.voole.hobbit2.camus.meta.common;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class CamusTopicPartitionStampKey extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CamusTopicPartitionStampKey\",\"namespace\":\"com.voole.hobbit2.camus.meta.common\",\"fields\":[{\"name\":\"topic\",\"type\":[\"string\",\"null\"]},{\"name\":\"partition\",\"type\":[\"int\",\"null\"]},{\"name\":\"categoryTime\",\"type\":[\"long\",\"null\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence topic;
  @Deprecated public java.lang.Integer partition;
  @Deprecated public java.lang.Long categoryTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public CamusTopicPartitionStampKey() {}

  /**
   * All-args constructor.
   */
  public CamusTopicPartitionStampKey(java.lang.CharSequence topic, java.lang.Integer partition, java.lang.Long categoryTime) {
    this.topic = topic;
    this.partition = partition;
    this.categoryTime = categoryTime;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return topic;
    case 1: return partition;
    case 2: return categoryTime;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: topic = (java.lang.CharSequence)value$; break;
    case 1: partition = (java.lang.Integer)value$; break;
    case 2: categoryTime = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'topic' field.
   */
  public java.lang.CharSequence getTopic() {
    return topic;
  }

  /**
   * Sets the value of the 'topic' field.
   * @param value the value to set.
   */
  public void setTopic(java.lang.CharSequence value) {
    this.topic = value;
  }

  /**
   * Gets the value of the 'partition' field.
   */
  public java.lang.Integer getPartition() {
    return partition;
  }

  /**
   * Sets the value of the 'partition' field.
   * @param value the value to set.
   */
  public void setPartition(java.lang.Integer value) {
    this.partition = value;
  }

  /**
   * Gets the value of the 'categoryTime' field.
   */
  public java.lang.Long getCategoryTime() {
    return categoryTime;
  }

  /**
   * Sets the value of the 'categoryTime' field.
   * @param value the value to set.
   */
  public void setCategoryTime(java.lang.Long value) {
    this.categoryTime = value;
  }

  /** Creates a new CamusTopicPartitionStampKey RecordBuilder */
  public static com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder newBuilder() {
    return new com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder();
  }
  
  /** Creates a new CamusTopicPartitionStampKey RecordBuilder by copying an existing Builder */
  public static com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder newBuilder(com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder other) {
    return new com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder(other);
  }
  
  /** Creates a new CamusTopicPartitionStampKey RecordBuilder by copying an existing CamusTopicPartitionStampKey instance */
  public static com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder newBuilder(com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey other) {
    return new com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder(other);
  }
  
  /**
   * RecordBuilder for CamusTopicPartitionStampKey instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CamusTopicPartitionStampKey>
    implements org.apache.avro.data.RecordBuilder<CamusTopicPartitionStampKey> {

    private java.lang.CharSequence topic;
    private java.lang.Integer partition;
    private java.lang.Long categoryTime;

    /** Creates a new Builder */
    private Builder() {
      super(com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.topic)) {
        this.topic = data().deepCopy(fields()[0].schema(), other.topic);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.partition)) {
        this.partition = data().deepCopy(fields()[1].schema(), other.partition);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.categoryTime)) {
        this.categoryTime = data().deepCopy(fields()[2].schema(), other.categoryTime);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing CamusTopicPartitionStampKey instance */
    private Builder(com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey other) {
            super(com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.SCHEMA$);
      if (isValidValue(fields()[0], other.topic)) {
        this.topic = data().deepCopy(fields()[0].schema(), other.topic);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.partition)) {
        this.partition = data().deepCopy(fields()[1].schema(), other.partition);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.categoryTime)) {
        this.categoryTime = data().deepCopy(fields()[2].schema(), other.categoryTime);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'topic' field */
    public java.lang.CharSequence getTopic() {
      return topic;
    }
    
    /** Sets the value of the 'topic' field */
    public com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder setTopic(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.topic = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'topic' field has been set */
    public boolean hasTopic() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'topic' field */
    public com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder clearTopic() {
      topic = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'partition' field */
    public java.lang.Integer getPartition() {
      return partition;
    }
    
    /** Sets the value of the 'partition' field */
    public com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder setPartition(java.lang.Integer value) {
      validate(fields()[1], value);
      this.partition = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'partition' field has been set */
    public boolean hasPartition() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'partition' field */
    public com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder clearPartition() {
      partition = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'categoryTime' field */
    public java.lang.Long getCategoryTime() {
      return categoryTime;
    }
    
    /** Sets the value of the 'categoryTime' field */
    public com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder setCategoryTime(java.lang.Long value) {
      validate(fields()[2], value);
      this.categoryTime = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'categoryTime' field has been set */
    public boolean hasCategoryTime() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'categoryTime' field */
    public com.voole.hobbit2.camus.meta.common.CamusTopicPartitionStampKey.Builder clearCategoryTime() {
      categoryTime = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public CamusTopicPartitionStampKey build() {
      try {
        CamusTopicPartitionStampKey record = new CamusTopicPartitionStampKey();
        record.topic = fieldSetFlags()[0] ? this.topic : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.partition = fieldSetFlags()[1] ? this.partition : (java.lang.Integer) defaultValue(fields()[1]);
        record.categoryTime = fieldSetFlags()[2] ? this.categoryTime : (java.lang.Long) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
