SELECT 
  FIRST_VALUE (DIM_OEM_ID) WITHIN
GROUP (
ORDER BY METRIC_PLAYBGNTIME DESC) AS oemid,
FIRST_VALUE (
  CASE
    WHEN METRIC_AVGSPEED IS NULL 
    OR BITRATE IS NULL 
    OR BITRATE * 1024 <= METRIC_AVGSPEED * 8 
    THEN 0 
    ELSE 1 
  END
) WITHIN
GROUP (
ORDER BY METRIC_PLAYBGNTIME DESC) AS is_low 
FROM
  HIVEORDERDETAILRECORD_PHOENIX
WHERE METRIC_PLAYBGNTIME IS NOT NULL 
  AND METRIC_PLAYBGNTIME > CAST(CURRENT_DATE() AS BIGINT) / 1000 - 10800 
  AND 
  CASE
    WHEN METRIC_PLAYENDTIME IS NOT NULL 
    AND METRIC_PLAYENDTIME > METRIC_PLAYBGNTIME 
    THEN - 1 
    ELSE 
    CASE
      WHEN METRIC_PLAYALIVETIME IS NOT NULL 
      AND METRIC_PLAYALIVETIME > METRIC_PLAYBGNTIME 
      THEN METRIC_PLAYALIVETIME 
      ELSE METRIC_PLAYBGNTIME 
    END 
  END >  CAST(CURRENT_DATE() AS BIGINT) / 1000 - 600 
GROUP BY DIM_USER_HID 