/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.voole.hobbit2.storm.test.kafka.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PlayEnd extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PlayEnd\",\"namespace\":\"com.voole.hobbit2.storm.test.kafka.avro\",\"fields\":[{\"name\":\"sessionId\",\"type\":\"string\"},{\"name\":\"stamp\",\"type\":\"long\"},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"PlayType\",\"symbols\":[\"BGN\",\"END\",\"ALIVE\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence sessionId;
  @Deprecated public long stamp;
  @Deprecated public com.voole.hobbit2.storm.test.kafka.avro.PlayType type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public PlayEnd() {}

  /**
   * All-args constructor.
   */
  public PlayEnd(java.lang.CharSequence sessionId, java.lang.Long stamp, com.voole.hobbit2.storm.test.kafka.avro.PlayType type) {
    this.sessionId = sessionId;
    this.stamp = stamp;
    this.type = type;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sessionId;
    case 1: return stamp;
    case 2: return type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sessionId = (java.lang.CharSequence)value$; break;
    case 1: stamp = (java.lang.Long)value$; break;
    case 2: type = (com.voole.hobbit2.storm.test.kafka.avro.PlayType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'sessionId' field.
   */
  public java.lang.CharSequence getSessionId() {
    return sessionId;
  }

  /**
   * Sets the value of the 'sessionId' field.
   * @param value the value to set.
   */
  public void setSessionId(java.lang.CharSequence value) {
    this.sessionId = value;
  }

  /**
   * Gets the value of the 'stamp' field.
   */
  public java.lang.Long getStamp() {
    return stamp;
  }

  /**
   * Sets the value of the 'stamp' field.
   * @param value the value to set.
   */
  public void setStamp(java.lang.Long value) {
    this.stamp = value;
  }

  /**
   * Gets the value of the 'type' field.
   */
  public com.voole.hobbit2.storm.test.kafka.avro.PlayType getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(com.voole.hobbit2.storm.test.kafka.avro.PlayType value) {
    this.type = value;
  }

  /** Creates a new PlayEnd RecordBuilder */
  public static com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder newBuilder() {
    return new com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder();
  }
  
  /** Creates a new PlayEnd RecordBuilder by copying an existing Builder */
  public static com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder newBuilder(com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder other) {
    return new com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder(other);
  }
  
  /** Creates a new PlayEnd RecordBuilder by copying an existing PlayEnd instance */
  public static com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder newBuilder(com.voole.hobbit2.storm.test.kafka.avro.PlayEnd other) {
    return new com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder(other);
  }
  
  /**
   * RecordBuilder for PlayEnd instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PlayEnd>
    implements org.apache.avro.data.RecordBuilder<PlayEnd> {

    private java.lang.CharSequence sessionId;
    private long stamp;
    private com.voole.hobbit2.storm.test.kafka.avro.PlayType type;

    /** Creates a new Builder */
    private Builder() {
      super(com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sessionId)) {
        this.sessionId = data().deepCopy(fields()[0].schema(), other.sessionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.stamp)) {
        this.stamp = data().deepCopy(fields()[1].schema(), other.stamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.type)) {
        this.type = data().deepCopy(fields()[2].schema(), other.type);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing PlayEnd instance */
    private Builder(com.voole.hobbit2.storm.test.kafka.avro.PlayEnd other) {
            super(com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.SCHEMA$);
      if (isValidValue(fields()[0], other.sessionId)) {
        this.sessionId = data().deepCopy(fields()[0].schema(), other.sessionId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.stamp)) {
        this.stamp = data().deepCopy(fields()[1].schema(), other.stamp);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.type)) {
        this.type = data().deepCopy(fields()[2].schema(), other.type);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'sessionId' field */
    public java.lang.CharSequence getSessionId() {
      return sessionId;
    }
    
    /** Sets the value of the 'sessionId' field */
    public com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder setSessionId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.sessionId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'sessionId' field has been set */
    public boolean hasSessionId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'sessionId' field */
    public com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder clearSessionId() {
      sessionId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'stamp' field */
    public java.lang.Long getStamp() {
      return stamp;
    }
    
    /** Sets the value of the 'stamp' field */
    public com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder setStamp(long value) {
      validate(fields()[1], value);
      this.stamp = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'stamp' field has been set */
    public boolean hasStamp() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'stamp' field */
    public com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder clearStamp() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'type' field */
    public com.voole.hobbit2.storm.test.kafka.avro.PlayType getType() {
      return type;
    }
    
    /** Sets the value of the 'type' field */
    public com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder setType(com.voole.hobbit2.storm.test.kafka.avro.PlayType value) {
      validate(fields()[2], value);
      this.type = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'type' field */
    public com.voole.hobbit2.storm.test.kafka.avro.PlayEnd.Builder clearType() {
      type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public PlayEnd build() {
      try {
        PlayEnd record = new PlayEnd();
        record.sessionId = fieldSetFlags()[0] ? this.sessionId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.stamp = fieldSetFlags()[1] ? this.stamp : (java.lang.Long) defaultValue(fields()[1]);
        record.type = fieldSetFlags()[2] ? this.type : (com.voole.hobbit2.storm.test.kafka.avro.PlayType) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
